### ISSUE TITLE
Fast CI time

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#107]
**Description**

Now the CI tests more than 13m, it's too slow.
https://github.com/datafuselabs/fuse-query/actions

Improve plans:
* Documetion or other non-codes level update no need CI
* ClickHouse github scripts here: https://github.com/ClickHouse/ClickHouse/tree/master/utils/github

**Comment by sundy-li** [comment]
Workspace may be the option to optimize rust build time.

**Comment by BohuTANG** [comment]
Seems github CI will build all the mod every time.

**Comment by BohuTANG** [comment]
#391
