### ISSUE TITLE
[bug] ClickHouse progress broken

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1071]
**Summary**

When we execute query with clickhouse client:
```
SELECT max(number), sum(number) FROM numbers_mt(1000000000) GROUP BY number % 3, number % 4, number % 5
```
The client progress not work after the patch: #931
cc @zhang2014

**Comment by BohuTANG** [comment]
I can't reproduce it now with master release.

**Comment by PsiACE** [comment]
I can‘t reproduce it either.
