### ISSUE TITLE
fuse-store panic after create remote table 

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#1134]
**Summary**

fuse-store panic after create table 

**How to reproduce**

start fuse-query and fuse-store

```
create database remote;
use remote;
mysql> use remote;
Database changed
mysql> create table t(c1 int, c2 int);
Query OK, 0 rows affected (0.01 sec)
```

Then restart the fuse-store process.

```
> ./target/debug/fuse-store
[2021-07-21T04:49:15Z INFO  fuse_store] Config { log_level: "INFO", log_dir: "./_logs", metric_api_address: "127.0.0.1:7171", flight_api_address: "127.0.0.1:9191", meta_api_host: "127.0.0.1", meta_api_port: 9291, meta_dir: "./_meta", boot: false }
[2021-07-21T04:49:15Z INFO  fuse_store] FuseStore v-0.1.0-92eed66-simd(1.55.0-nightly-2021-07-21T01:20:42.134404693+00:00)
[2021-07-21T04:49:15Z INFO  fuse_store] Metric API server listening on 127.0.0.1:7171
[2021-07-21T04:49:15Z INFO  fuse_store] RPC API server listening on 127.0.0.1:9191
Jul 21 12:49:15.011  INFO fuse_store::api::rpc_service: flight addr: 127.0.0.1:9191
thread 'main' panicked at 'RPC service error: Code: 2402, displayText = exist: id=Ok(0).', fusestore/store/src/bin/fuse-store.rs:43:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

cc @dantengsky @drmingdrmer 

`rm -rf _meta`  works, maybe  there are some dirty files.

**Comment by drmingdrmer** [comment]
> `rm -rf _meta` works, maybe there are some dirty files.

Yes the current version of fuse-store writes raft log to disk, and will reload the old data.
Removing `_meta` or using a `TempDir`for testing would solve this problem.

The default fuse-store Config uses `_meta` as data dir. Maybe the testing script needs to give fuse store a unique dir for every round of test.
```rust
    #[structopt(
        long,
        env = "FUSE_STORE_META_DIR",
        default_value = "./_meta",
        help = "The dir to store persisted meta state, including raft logs, state machine etc."
    )]
    pub meta_dir: String,
```

**Comment by sundy-li** [comment]
Ok, so it's caused by some bugs in the meta reload?

**Comment by BohuTANG** [comment]
@drmingdrmer 
From your information, `FUSE_STORE_META_DIR` should set a different value for test.

**Comment by drmingdrmer** [comment]
> Ok, so it's caused by some bugs in the meta reload?

@sundy-li 
Sorry seems I misunderstood. If it panics just after restarting it is store's fault.

Meanwhile fuse-store does not support restart yet. The codes is now in a transitional state migrating mem-store to on-disk-store. Restarting does not work until raft state machine is migrated(log is on-disk while state machine is still pure memory). 

I'm gonna fix the restart panic in a few days.
But the inconvenience with a stateful service will continue that `_meta` must be removed manually to have a clean test env from now on.

@BohuTANG 
A unittest always creates a tmp dir to run. But when startup from CLI, where the data dir is can not be controlled from inside fuse-store.
