### ISSUE TITLE
[FR] Provide some computing service interfaces to the fuse store

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/datafuse#1153]
**Summary**

FuseStore is multi tenant. It is designed to provide services for multiple FuseQuery clusters (any resource is expensive). may we should to unload some unnecessary overhead into FuseQuery (welcome to discuss in this issue).

1. offline index build
2. storage data merge task
3. CBO analysis

**Comment by zhang2014** [comment]
The FuseStore may be used to coordinate and track these tasks, and may execute them on its own when necessary (when query is busy)

**Comment by BohuTANG** [comment]
Ok, I will create a track issue for it

**Comment by drmingdrmer** [comment]
What does the **index** mean exactly? Is it a mysql secondary index like thing, or the statistics of every column such as max/min/avg/sum?

**Comment by BohuTANG** [comment]
I think here the 'index' is the secondary index as in MySQL, and clustering in snowflake.
But this issue should emphasize the manageability of the store, such as adding more management api to be invoked through additional systems, for example, we will have a system called 'fusebrain', and he analysis the query history metrics and do some pruning and clustering if user's query is hot, or something like this :)

**Comment by BohuTANG** [comment]
The architecture has been adjusted, so to avoid misunderstandings,  close this issue.
