### ISSUE TITLE
Provides a global version number for database meta

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/datafuse#1168]
**Summary**

We need a global version number for the database meta information, which will be increased for each DDL statement if executed successfully (or have externally visible effects).

**Comment by drmingdrmer** [comment]
Yes a `seq` is going to be added to every meta data.
@ariesdevil has been working on this: https://github.com/datafuselabs/datafuse/issues/1139

**Comment by dantengsky** [comment]
:sob: I am working on it  #1169

**Comment by dantengsky** [comment]
PR #

**Comment by drmingdrmer** [comment]
> 😭 I am working on it #1169

Hm... after reading your codes I see that they are two different things.
