### ISSUE TITLE
Considering migrate to arrow2

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#1170]
**Summary**

From Reddit: https://www.reddit.com/r/rust/comments/ooyhn1/release_of_arrow2_01_and_parquet2_01/

Features depends on arrow2, to be filled

- [x]  jorgecarleitao/arrow2#215
- [ ] https://github.com/jorgecarleitao/arrow2/issues/245

**Comment by sundy-li** [comment]
https://github.com/jorgecarleitao/arrow2/issues/215

**Comment by jorgecarleitao** [comment]
Let me know if you have any blocker from the arrow2's side of things; happy to help / accommodate.

The limit option has been released [as part of v0.2](https://github.com/jorgecarleitao/arrow2/releases/tag/v0.2.0).

**Comment by BohuTANG** [comment]
@jorgecarleitao 
Sure, thank you.
Actually, @sundy-li is working on it https://github.com/datafuselabs/datafuse/pull/1239
