### ISSUE TITLE
[bug] Metadata was not cleaned up when drop a remote table.

### ISSUE THREAD

**Issue by zhyass** [datafuselabs/datafuse#1197]
**Summary**

I create a remote table and insert into some data, then drop the table and create again. I can get the previously inserted data. Maybe this is a bug?

**How to reproduce**

**Error message and/or stacktrace**

![WechatIMG652](https://user-images.githubusercontent.com/34016424/127114442-3d3e189d-7c43-4ef1-ad89-6c51fc6a05bb.jpeg)

**Additional context**

**Comment by BohuTANG** [comment]
Yes, it's bug.
cc @dantengsky
