### ISSUE TITLE
common/io crate to have bianary serde

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#1215]
**Summary**

Currently, we serde the aggregate function state by *serde/json*, but it's not efficient as binary serde.

Eg:
avg_state
Current each state item has useless keys, and it's not compact format.
```
{"sum":xxx, "count":  xxx}
```

**Comment by PsiACE** [comment]
change to [bincode](https://crates.io/crates/bincode) ?

**Comment by sundy-li** [comment]
> change to [bincode](https://crates.io/crates/bincode) ?

Looks great,  I have looked into this crate, but I think to use write_variant for the length of vectors or Strings is better than u64. So I create a new simple serde in common/io. 

If we found another one is more efficient, we can refactor this in common/io later.
