### ISSUE TITLE
[store] refactor: remove fusestore/store/src/engine/mem_engine.rs

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#1225]
**Summary**

`mem_engine` isn't used anymore

**Comment by SGZW** [comment]
can i pick this issue?

**Comment by ariesdevil** [comment]
Duplicated https://github.com/datafuselabs/datafuse/issues/1099

**Comment by drmingdrmer** [comment]
@SGZW 
Thanks my man!
Moving so quickly!
