### ISSUE TITLE
Add config for DFS storage and raft meta storage, e.g. a local dir.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#1250]

**Comment by SGZW** [comment]
/assignme

i want to join development of fusestore

**Comment by SGZW** [comment]
i want to join development of fusestore,  can i pick this?

**Comment by drmingdrmer** [comment]
@SGZW Thanks your contribution man!

I have not made time to elaborate the issue yet... Sorry I got caught up in something else last night:

First a new config field need to be added: 
https://github.com/datafuselabs/datafuse/blob/4bf2bed809c67d7ebabba7839519a3b293bac574/fusestore/store/src/configs/config.rs#L30-L35

For letting unit tests pass, `new_test_context()` needs to give the new field a `TempDir`: 
https://github.com/datafuselabs/datafuse/blob/4bf2bed809c67d7ebabba7839519a3b293bac574/fusestore/store/src/tests/service.rs#L51-L90

And when `StoreServer` starts, it should read the `config` instead of making a temp-dir itself:
https://github.com/datafuselabs/datafuse/blob/4bf2bed809c67d7ebabba7839519a3b293bac574/fusestore/store/src/api/rpc_service.rs#L36-L38

**Comment by SGZW** [comment]
>          config.meta_no_sync = true;

when using raft library,  generally we has fsm snapshot dir / raft log dir / fsm data dir (when fsm is Persistent).  so fuse-store just keep above three dir in one ?

**Comment by drmingdrmer** [comment]
> > ```
> >      config.meta_no_sync = true;
> > ```
> 
> when using raft library, generally we has fsm snapshot dir / raft log dir / fsm data dir (when fsm is Persistent). so fuse-store just keep above three dir in one ?

What is fsm? 

A FuseStore has two major components: a local-fs and a MetaNode.
Local-fs needs a configurable local dir path, which is the only config field it lacks now.

`MetaNode` in future needs only one dir path to open a `sled::Db`. The multi db mode is gonna be replaced with the single db mode.

**Comment by SGZW** [comment]
> > > ```
> > >      config.meta_no_sync = true;
> > > ```
> > 
> > 
> > when using raft library, generally we has fsm snapshot dir / raft log dir / fsm data dir (when fsm is Persistent). so fuse-store just keep above three dir in one ?
> 
> What is fsm?
> 
> A FuseStore has two major components: a local-fs and a MetaNode.
> Local-fs needs a configurable local dir path, which is the only config field it lacks now.
> 
> `MetaNode` in future needs only one dir path to open a `sled::Db`. The multi db mode is gonna be replaced with the single db mode.

yes, fsm is Finite State Machine， in fusestore，this is sled::Db, all meta info persist in the sled::Db

**Comment by drmingdrmer** [comment]
Hm... it is not finite(a key-value store is a vector space with infinite dimensions). Let's just call it state machine. :DDD
