### ISSUE TITLE
How is this done?

### ISSUE THREAD

**Issue by simPod** [datafuselabs/datafuse#1287]
Hi, is this built on top of clickhouse? What are the enhancements?

I have checked https://datafuse.rs/overview/architecture/ but there's not much detail how does it work internally so it's kind of hard to decide whether to use or not. Thanks!

**Comment by gauss1314** [comment]
In my opinion, this is not built on top of clickhouse. Datafuse is build from scratch inspired by clickhouse and arrow for cloud native.
Datafuse is currently in Alpha and is not ready to be used in production, but you can test it or participate in development.
Here are some design details: https://datafuse.rs/rfcs/store/0001-store-design/

**Comment by BohuTANG** [comment]
In another perspective , we can think of datafuse as a cloud version of ClickHouse, where compute and storage are separated and storage is multi-tenant.

**Comment by simPod** [comment]
Thank you for clarifications!
