### ISSUE TITLE
[CLI] Support to fetch, download, switch different fuse-query and fuse-store version

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/datafuse#1296]
**Summary**
API:
fusecli fetch --version v0.4.33-nightly
download given fuse-query or fuse-store version in release
fusecli fetch
download the latest fuse-query or fuse-store version
fusecli list
will show all fetched version, and annotate on version which is used now
fusecli switch --version v0.4.33-nightly
switch the version people want

**Comment by BohuTANG** [comment]
There already a issue for tracking it:https://github.com/datafuselabs/datafuse/issues/938

And CLI designed including two parts:
1. main command
2. sub command

For example:
```
 datafuse-cli package fetch [flags]
```

main command: `package`
sub command: `fetch`

It seems more make sense.

**Comment by BohuTANG** [comment]
Duplicated with #938
