### ISSUE TITLE
[store] feature: create a global sled db for all use in a process.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#1311]

**Comment by SGZW** [comment]
what the mean of "all use"? state machine and raft log and anything else ?

**Comment by drmingdrmer** [comment]
raft state, raft log, raft state machine.
Meanwhile these 3 components depends on sled::Db.

There is some testing ongoing to ensure whether this modification would fix the deadlock bug.

It seems using only one sled db still has chance of deadlock with concurrent calls to `sled::Tree::flush_async()` :(((

**Comment by SGZW** [comment]
Thanks,  so the purpose of this issue is to solve the deadlock? Can you give more info about this dead lock or this problem is the internal of sled::Tree ?

**Comment by drmingdrmer** [comment]
I did not yet dig deep enough yet. A deadlock occurs when using `sled::Tree::flush_async()` on multiple sled::Db in multiple `tokio::runtime`.
I have a snippet to reduce this problem:
https://github.com/drmingdrmer/sledtest/blob/main/src/main.rs

But in datafuse unittest, a single sled db has this problem too. (sled doc states that a process should open only one sled::Db which I thought is the cause of the deadlock.). The root may be in the concurrency control about `flush()` and `flush_async()`.
I've been trying to build another snippet to reproduce this.

When a tokio is dropped, it triggers a sled tree dropping.  Then another `flush()` is triggered when dropping the sled tree. 
At this point, a previous ongoing `flush_async` has chance to block forever.
