### ISSUE TITLE
[test-infra] change the status to running

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1339]
**Summary**
For the CI `/run-perf master`, `pending` may not be a good status, since they are already running in backgroud, change to `running`? 

<img src="https://user-images.githubusercontent.com/172204/128621465-8ba82620-8b59-42ca-841e-f39c30698287.png" align="center" style="zoom:10%;" />

**Comment by ZhiHanZ** [comment]
github status only supports 4 types: error, failure, success and pending, and seems like we could not define status by oursleves.
https://docs.github.com/en/rest/reference/repos#statuses
