### ISSUE TITLE
Build for Debug Error 

### ISSUE THREAD

**Issue by wangzhen11aaa** [datafuselabs/datafuse#1340]
Error 
Running `cargo build --bin=fuse-query --package=fuse-query --message-format=json`...
   Compiling common-flights v0.1.0 (/Users/wangzhen/RustProject/datafuse/common/flights)
error[E0432]: unresolved import `tonic::transport::ClientTlsConfig`
  --> common/flights/src/dns_resolver.rs:25:5
   |
25 | use tonic::transport::ClientTlsConfig;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ClientTlsConfig` in `transport`

error[E0282]: type annotations needed
   --> common/flights/src/dns_resolver.rs:151:45
    |
151 |                     let client_tls_config = Self::client_tls_config(&conf).await.map_err(|e| {
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
    |
    = note: type must be known at this point

error[E0599]: no method named `tls_config` found for struct `Endpoint` in the current scope
   --> common/flights/src/dns_resolver.rs:157:29
    |
157 |                     builder.tls_config(client_tls_config).map_err(|e| {
    |                             ^^^^^^^^^^ method not found in `Endpoint`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0282, E0432, E0599.

For more information about an error, try `rustc --explain E0282`.

error: could not compile `common-flights` due to 4 previous errors

**Operating system**
Mac

OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**rust version**
```text
$ rustc --version
rustc 1.56.0-nightly (e3b1c12be 2021-08-02)
$ cargo --version
cargo 1.55.0-nightly (d21c22870 2021-07-26)
```

**Datafuse git version**

**Comment by BohuTANG** [comment]
Could you please try:
```
make clean
make setup
make build-debug
```

**Comment by wangzhen11aaa** [comment]
> Could you please try:
> 
> ```
> make clean
> make setup
> make build-debug
> ```

tonic = { version = "0.4.3", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
These features of tonic should be added in Cargo.toml of flights module.

**Comment by dantengsky** [comment]
@wangzhen11aaa  I think @sundy-li has fixed this issue, would you please try the lasted master branch again?

**Comment by dantengsky** [comment]
and please feel free to re-open this issue, if the bug is still there :D

**Comment by wangzhen11aaa** [comment]
> and please feel free to re-open this issue, if the bug is still there :D

It's ok now.

**Comment by dantengsky** [comment]
> > and please feel free to re-open this issue, if the bug is still there :D
> 
> It's ok now.

got it, and thanks for opening the issue :D
