### ISSUE TITLE
executes `TruncateTableAction` by using raft consensus protocol

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/datafuse#1349]
**Summary**

If I get it right, `TruncateTableAction` is being executed by modifying the state of `MetaStore` directly, which is correct in single-node store deployment. But for multi-nodes deployment of `Store`,  `TruncateTableAction` should be performed by using the raft consensus protocol, like "CreateTable/Databse" does

**Comment by drmingdrmer** [comment]
> /assignme

@ariesdevil 
Finish the issues you are working on before taking another one.

**Comment by drmingdrmer** [comment]
@ariesdevil
Or release the issue you are working on if you've moved to another one.

**Comment by drmingdrmer** [comment]
https://github.com/datafuselabs/datafuse/blob/4236ce19ca5abd589dc1391f15035ab7f987976c/fusestore/store/src/executor/storage_handlers.rs#L31-L53

The modification includes: 
- Submit a `LogEntry` to `MetaNode` throught `write()` method. A good reference is: https://github.com/datafuselabs/datafuse/blob/4236ce19ca5abd589dc1391f15035ab7f987976c/fusestore/store/src/executor/kv_handlers.rs#L26-L47
- Move the update from `RequestHandler<TruncateTableAction>` into `StateMachine::apply`.
- Add or update corresponding tests.

**Comment by drmingdrmer** [comment]
@SGZW This issue involves codes that still need some refactor and may be misleading when you read it.
If you have any question about the current code base, just let us know.

**Comment by SGZW** [comment]
> @SGZW This issue involves codes that still need some refactor and may be misleading when you read it.
> If you have any question about the current code base, just let us know.

ok, thanks
