### ISSUE TITLE
Support SHOW TABLES LIKE `pattern` and Where expr

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/datafuse#1388]
**Summary**

https://www.db-fiddle.com/f/9941isstm4v3dvWhye9ZPg/0
```
CREATE TABLE `table_1`(id varchar(200));
SHOW TABLES LIKE 'TABLE_1';
SHOW TABLES LIKE '%unknown%';

SHOW TABLES LIKE 'table_1';
SHOW TABLES LIKE '%_1';
SHOW TABLES LIKE 'ta%';
SHOW TABLES LIKE '%le%';

SHOW TABLES where xxx;
```

**Comment by mapleFU** [comment]
This tasks seems similiar to https://github.com/datafuselabs/datafuse/issues/1390 .
Seems I need to call `get_all_tables` in `Catalog`, and using regex to check if any table matches the user's command. Did I catch it?

**Comment by sundy-li** [comment]
> Seems I need to call get_all_tables in Catalog, and using regex to check if any table matches the user's command

No, just convert the `show tables` to  `select name from system.tables` and append the like filters to where clause.

**Comment by sundy-li** [comment]
Refer: https://dev.mysql.com/doc/refman/8.0/en/show-tables.html

```
SHOW [EXTENDED] [FULL] TABLES
    [{FROM | IN} db_name]
    [LIKE 'pattern' | WHERE expr]
```
We can extend the show query with either Like 'pattern' or Where expr.

**Comment by mapleFU** [comment]
@sundy-li so, I should modify it in `sql/plan_parser.rs`:

```
pub fn statement_to_plan(&self, statement: &DfStatement) -> Result<PlanNode>
```

What I need to do is modifying this?

**Comment by mapleFU** [comment]
If I catched it, let me pickup this issue. I will finish it before this saturday.

**Comment by BohuTANG** [comment]
@mapleFU 
you can take it with the comments '/assignme'
Thank you
