### ISSUE TITLE
Support SHOW TABLES WHERE statement

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/datafuse#1389]
**Summary**

https://www.db-fiddle.com/f/xkhhN3tfxXnUepeDPJ86rA/1
```
CREATE TABLE test_table(id varchar(200));
SHOW TABLES WHERE `Tables_in_test` = 'ss';
SHOW TABLES WHERE `Tables_in_test` = 'test_table';
```

**Comment by zhang2014** [comment]
@SGZW 
It seems @maplefu has solved this problem

**Comment by SGZW** [comment]
> @SGZW
> It seems @mapleFU has implemented this : )

thanks for notice

**Comment by mapleFU** [comment]
Seems that we can close this issue @zhang2014

**Comment by zhang2014** [comment]
> Seems that we can close this issue @zhang2014

Yes.

> thanks for notice

 @SGZW thank you for your contribution too.
