### ISSUE TITLE
[common] add common/dal mod

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1407]
**Summary**

common/datasources mod may including:
```
- dal: interface for the shared storage such as S3
```

**Comment by dantengsky** [comment]
In the `datasource` abstraction, should we support `create databases by engine` like CK 

https://clickhouse.tech/docs/en/engines/database-engines/

that is, although metadata is saved in a single meta store ( no more local metadata ), databases can be re-interpreted by different engines.

**Comment by dantengsky** [comment]
In addition to the table engine (if I get it right) in issue #1316

**Comment by BohuTANG** [comment]
> In the `datasource` abstraction, should we support `create databases by engine` like CK
> 
> https://clickhouse.tech/docs/en/engines/database-engines/
> 
> that is, although metadata is saved in a single meta store ( no more local metadata ), databases can be re-interpreted by different engines.

The database engine later?
Here I assume that is only a constraint, not affect our cloud arch.

**Comment by dantengsky** [comment]
Ok

**Comment by BohuTANG** [comment]
Renamed 
cc @dantengsky

**Comment by dantengsky** [comment]
got it
