### ISSUE TITLE
[CI] Add slack notification on performance test

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/datafuse#1413]
**Summary**

Description for this feature.
For timely troubleshooting, it is helpful

**Comment by jackwener** [comment]
Maybe I can have a try to fix.

**Comment by jackwener** [comment]
There aren't many details is provided.
When is the CI of slack notification triggered?
And, what should CI send message?

**Comment by BohuTANG** [comment]
This may is a slack api invoke after performance test finished cc @ZhiHanZ

**Comment by ZhiHanZ** [comment]
basically, slack notification need to sync running status of performance tests in github actions to slack webhook including test start, fail, and success
