### ISSUE TITLE
[Performance Test] Increase performance test accuracy by running more iterations

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/datafuse#1453]
**Summary**
Currently performance test standalone takes about 8 minutes to run, and run 10 iterations to each query, here for more accueracy result convergence consideration, we could bump test to 100 iterations

**Comment by PsiACE** [comment]
80 minutes is too long. I think this should be available as an option.

**Comment by ZhiHanZ** [comment]
> 80 minutes is too long. I think this should be available as an option.

only about 2 minutes are used for running performance tests, other time is for data loading, env set up etc
