### ISSUE TITLE
[Test] Flaky Unit Test

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/datafuse#1494]
**Summary**
https://github.com/datafuselabs/datafuse/pull/1491/checks?check_run_id=3348449605

**Comment by PsiACE** [comment]
https://github.com/datafuselabs/datafuse/runs/3368544958#step:5:1092

**Comment by sundy-li** [comment]
https://github.com/datafuselabs/datafuse/runs/3378269740#step:5:1105

```
---- meta_service::raftmeta_test::test_meta_node_snapshot_replication stdout ----
Error: Raft is shutting down

Caused by:
    Raft is shutting down
thread 'meta_service::raftmeta_test::test_meta_node_snapshot_replication' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/test/src/lib.rs:194:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by BohuTANG** [comment]
> https://github.com/datafuselabs/datafuse/runs/3378269740#step:5:1105
> 
> ```
> ---- meta_service::raftmeta_test::test_meta_node_snapshot_replication stdout ----
> Error: Raft is shutting down
> 
> Caused by:
>     Raft is shutting down
> thread 'meta_service::raftmeta_test::test_meta_node_snapshot_replication' panicked at 'assertion failed: `(left == right)`
>   left: `1`,
>  right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/test/src/lib.rs:194:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Also commented here: https://github.com/datafuselabs/datafuse/issues/548#issuecomment-902356436

**Comment by drmingdrmer** [comment]
> https://github.com/datafuselabs/datafuse/runs/3378269740#step:5:1105
> 
> ```
> ---- meta_service::raftmeta_test::test_meta_node_snapshot_replication stdout ----
> Error: Raft is shutting down
> 
> Caused by:
>     Raft is shutting down
> thread 'meta_service::raftmeta_test::test_meta_node_snapshot_replication' panicked at 'assertion failed: `(left == right)`
>   left: `1`,
>  right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/test/src/lib.rs:194:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Got it!
