### ISSUE TITLE
Cannot create table?

### ISSUE THREAD

**Issue by zhangysh1995** [datafuselabs/datafuse#15]
Hi, I’m new to both this database and ClickHouse, could I know how to insert data to the database?

**Comment by BohuTANG** [comment]
hi,
This project is still in early stage.
As a cloud data warehouse, we have to explore the QUERY mode first before starting writes DDL and DML.
QUERY mode now including query plan, plan to processor, processor running on distributed node.
As for writes, we also build execution plans and the data will be sent to the fuse-store and eventually stored in an object store like s3, it's simply than QUERY.
Thank you for your interest, the docs will add more details about it soon.

**Comment by BohuTANG** [comment]
#134
