### ISSUE TITLE
Add cluster mode for fuse-test

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#151]
**Summary**

For fuse-test supports Cluster and Standalone(now support), the init plans:
[1] Start two servers in https://github.com/datafuselabs/fuse-query/blob/master/docker/stateless/run.sh#L4
 
 ```
  # node-9090
  sudo nohup /fuse-query &

  # node-9091
  sudo nohup /fuse-query --http-api-address=127.0.0.1:8081 --metric-api-address=127.0.0.1:7071 --mysql-handler-port=3308 --rpc-api-address=127.0.0.1:9091&
  ```

[2] Add nodes to 127.0.0.1:9090(Coordinator)
```
#Add node-9090 
curl http://127.0.0.1:8080/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"9090","address":"127.0.0.1:9090","cpus":8}'

#Add node-9091
curl http://127.0.0.1:8080/v1/cluster/add -X POST -H "Content-Type: application/json" -d '{"name":"9091","address":"127.0.0.1:9091","cpus":8}'
```

[3] node-9090 is in cluster with 2 nodes, and node-9091 is single stand
[4] Add 1_cluster for cluster mode test?

**Comment by sundy-li** [comment]
I prefer to keep stateless tests just for single node testing.

And we can have integration-tests for cluster mode testing.

**Comment by BohuTANG** [comment]
> I prefer to keep stateless tests just for single node testing.
> 
> And we can have integration-tests for cluster mode testing.

LGTM

**Comment by BohuTANG** [comment]
Move to #391
