### ISSUE TITLE
[improvement]  Add `SHOW TABLES LIKE pattern and Where expr` to doc

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1528]
**Summary**

Add to doc:
```
CREATE TABLE `table_1`(id varchar(200));
SHOW TABLES LIKE 'TABLE_1';
SHOW TABLES LIKE '%unknown%';

SHOW TABLES LIKE 'table_1';
SHOW TABLES LIKE '%_1';
SHOW TABLES LIKE 'ta%';
SHOW TABLES LIKE '%le%';

SHOW TABLES where xxx;
```
issue: #1388

**Comment by mapleFU** [comment]
Since I fixed #1388 , I will complete the document about it .
Would you mind tell me where is the document for the project? @BohuTANG

**Comment by sundy-li** [comment]
![image](https://user-images.githubusercontent.com/3325189/130209977-434a7154-6c42-4d3f-ae08-63ca6fea5745.png)

**Comment by mapleFU** [comment]
I will add it before this Sunday.

**Comment by BohuTANG** [comment]
> I will add it before this Sunday.

By the way, we can run https://datafuse.rs website locally:
1. cd website/datafuse
2. make install
3. make run

**Comment by mapleFU** [comment]
Thanks! I tried it and it works well!
By the way, why does datafuse make all modules, even including website, in
one repo?
And does it better to rebase commits before merging the branch to master?

BohuTANG ***@***.***> 于2021年8月20日周五 下午5:31写道：

**Comment by BohuTANG** [comment]
> Thanks! I tried it and it works well! By the way, why does datafuse make all modules, even including website, in one repo? 

Aha, At least for now we don't like to maintain multiple repos, and it works well all in one(issue/stars/contributors) :thinking: 

> And does it better to rebase commits before merging the branch to master? BohuTANG ***@***.***>

This already talked many times, the reasons:
We want to keep track of all git commits, and from which the datafuse-bot will extract information to generate our release log.
You can see them here:
https://github.com/datafuselabs/datafuse/releases
