### ISSUE TITLE
Stateless-test fails on my laptop

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#1531]
**Remote** db/table return values with additional quotes that make `stateless-test` fail.

Reproduce:
- `make stateless-test`

Environment:
- OS: mac os 10.15.5 (19F101)
- mysql: mysql  Ver 8.0.25 for macos10.15 on x86_64 (Homebrew)
- datafuse:
- commit:
```
5eb2ba8796f1e20b03dd00459eb6d159ca216b6e
Merge: 08ca3de0f 51c7e89e6
Author: DatafuseBot <82190365+datafuse-bot@users.noreply.github.com>
Date:   Fri Aug 20 09:41:45 2021 +0800
```

Output:

```
09_0000_remote_create_table:                                            [ OK ]
09_0001_remote_insert:                                                  [ FAIL ] - result differs with:
--- /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0001_remote_insert.result        2021-08-18 18:33:56.000000000 +0800
+++ /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0001_remote_insert.stdout        2021-08-20 02:43:19.000000000 +0800
@@ -1,3 +1 @@
-1      1       1
-2      2       "2"-"2"
-3
+NULL

09_0002_remote_truncate_table:                                          [ FAIL ] - result differs with:
--- /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0002_remote_truncate_table.result        2021-08-18 18:33:56.000000000 +0800
+++ /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0002_remote_truncate_table.stdout        2021-08-20 02:43:19.000000000 +0800
@@ -1,2 +1,2 @@
-1      v1
-2      v2
+'1'    'v1'
+'2'    'v2'

09_0003_remote_drop_table:                                              [ FAIL ] - result differs with:
--- /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0003_remote_drop_table.result    2021-08-18 18:33:56.000000000 +0800
+++ /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0003_remote_drop_table.stdout    2021-08-20 02:43:20.000000000 +0800
@@ -1,6 +1,6 @@
-1      v1
-2      v2
-t2_1   t2_v1
-t2_2   t2_v2
-t2_1   t2_v1
-t2_2   t2_v2
+'1'    'v1'
+'2'    'v2'
+'t2_1' 't2_v1'
+'t2_2' 't2_v2'
+'t2_1' 't2_v1'
+'t2_2' 't2_v2'
```

**Comment by dantengsky** [comment]
is it flaky or deterministic?
Can not re-produced it in a Linux box yet (commit #5eb2ba8796f1e20b03dd00459eb6d159ca216b6e )

**Comment by dantengsky** [comment]
The last two cases may be something related to the mysql-client? have you upgraded MySQL client recently?

**Comment by PsiACE** [comment]
This problem can be reproduced on my old laptop. But it should be flaky.

**Comment by drmingdrmer** [comment]
Deterministic... Only tests that involve remote access have this issue. 🤔

**Comment by drmingdrmer** [comment]
> The last two cases may be something related to the mysql-client? have you upgraded MySQL client recently?

My client is mysql: mysql Ver 8.0.25 for macos10.15 on x86_64 (Homebrew)

I did not upgrade it(manually 🤔 ) since the last time I got `stateless-test` pass.

**Comment by dantengsky** [comment]
@PsiACE @drmingdrmer 
roger

**Comment by dantengsky** [comment]
@sundy-li bro, need your help: 

> -1      v1
> -2      v2
> -t2_1   t2_v1
> -t2_2   t2_v2
> -t2_1   t2_v1
> -t2_2   t2_v2
> +'1'    'v1'
> +'2'    'v2'
> +'t2_1' 't2_v1'
> +'t2_2' 't2_v2'
> +'t2_1' 't2_v1'
> +'t2_2' 't2_v2'

these two results only different in single quotes, and those single quotes are removed from `09_0002_remote_truncate_table.result` and `09_0003_remote_drop_table.result` on 08-17. any hints of this issue?

**Comment by dantengsky** [comment]
@drmingdrmer 

have you found any panic/crash log messages in the `nohup` file, related to the following case?

> 09_0000_remote_create_table:                                            [ OK ]
> 09_0001_remote_insert:                                                  [ FAIL ] - result differs with:
> --- /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0001_remote_insert.result        2021-08-18 18:33:56.000000000 +0800
> +++ /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0001_remote_insert.stdout        2021-08-20 02:43:19.000000000 +0800
> @@ -1,3 +1 @@
> -1      1       1
> -2      2       "2"-"2"
> -3
> +NULL

**Comment by dantengsky** [comment]
@drmingdrmer 

- Can not reproduce any of the failure cases in my dev box for the given commit  (repeated `make stateless-test`  100+ times).

- the last two failure cases may be caused by the "miss-matched" MySQL client version, I am using 

> mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

please do me a favor, and do the following check:



~~~
> make stateless-test
> #leave the processes alive
> mysql -uroot -h127.0.0.1 -P3307 -s < $PROJECT_ROOT/tests/suites/0_stateless/09_0003_remote_drop_table.sql
~~~

In my dev box, I got:

> 1	v1
> 2	v2
> t2_1	t2_v1
> t2_2	t2_v2
> t2_1	t2_v1
> t2_2	t2_v2

What's your result?

**Comment by sundy-li** [comment]
> these two results only different in single quotes, and those single quotes are removed from

Yes, because single quotes are removed during inseration, and strings will out displayed with quotes by default.

I think it's the reason for different `datafuse-query` and  `datafuse-store` ?
Maybe your `datafuse-query` is not up to  date.

**Comment by dantengsky** [comment]
@sundy-li  thanks. I can not reproduce the test failures, things are going well in my local test env, maybe the MySQL client is not "compatible"?  @drmingdrmer  is using mysql Ver 8.0.25, mine is 8.0.26. verifying if that is the case

**Comment by dantengsky** [comment]
I do not have any clues for the first failure:

> 09_0001_remote_insert:                                                  [ FAIL ] - result differs with:
> --- /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0001_remote_insert.result        2021-08-18 18:33:56.000000000 +0800
> +++ /Users/drdrxp/xp/vcs/github.com/drmingdrmer/fuse-query/tests/suites/0_stateless/09_0001_remote_insert.stdout        2021-08-20 02:43:19.000000000 +0800
> @@ -1,3 +1 @@
> -1      1       1
> -2      2       "2"-"2"
> -3
> +NULL

I guess there is a panic somewhere. 

@drmingdrmer  please ensure not to use a stale version of fuse-query, there is a known issue that is fixed by #1489 will fail testcase `09_0001_remote_insert` in 1-query 1-store settings (which `make stateless-test` uses )

As @sundy-li  mentioned: 
> Maybe your datafuse-query is not up to date.

**Comment by drmingdrmer** [comment]
> @drmingdrmer
> 
> have you found any panic/crash log messages in the `nohup` file, related to the following case?

@dantengsky I've seen several lines like this:
(not sure if it is related. The complete `nohup.out` is attached too.)

```
[2021-08-20T03:25:53Z ERROR common_flights::impls::storage_api_impl] failed to convert DataBlock to RecordBatch , breaking out, Code: 1002, displayText = Invalid argument error: column types must match schema types, expected UInt32 but found LargeUtf8 at column index 0.

       0: backtrace::backtrace::libunwind::trace
                 at /Users/drdrxp/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.61/src/backtrace/libunwind.rs:90:5
          backtrace::backtrace::trace_unsynchronized
                 at /Users/drdrxp/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.61/src/backtrace/mod.rs:66:5
       1: backtrace::backtrace::trace
                 at /Users/drdrxp/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.61/src/backtrace/mod.rs:53:14
       2: backtrace::capture::Backtrace::create
                 at /Users/drdrxp/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.61/src/capture.rs:176:9
       3: backtrace::capture::Backtrace::new
                 at /Users/drdrxp/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.61/src/capture.rs:140:22
       4: common_exception::exception::ErrorCode::from_std_error
                 at common/exception/src/exception.rs:375:65
       5: <common_exception::exception::ErrorCode as core::convert::From<arrow2::error::ArrowError>>::from
                 at common/exception/src/exception.rs:323:9
       6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
                 at /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/core/src/result.rs:1915:27
       7: common_datablocks::data_block::<impl core::convert::TryFrom<common_datablocks::data_block::DataBlock> for arrow2::record_batch::RecordBatch>::try_from
                 at common/datablocks/src/data_block.rs:148:12
       8: common_flights::impls::storage_api_impl::<impl common_store_api::storage_api::StorageApi for common_flights::store_client::StoreClient>::append_data::{{closure}}::{{closure}}
```

[nohup.out.zip](https://github.com/datafuselabs/datafuse/files/7025016/nohup.out.zip)

**Comment by drmingdrmer** [comment]
> @drmingdrmer
> 
> * Can not reproduce any of the failure cases in my dev box for the given commit  (repeated `make stateless-test`  100+ times).
> * the last two failure cases may be caused by the "miss-matched" MySQL client version, I am using
> 
> > mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
> 
> please do me a favor, and do the following check:
> 
> ```
> > make stateless-test
> > #leave the processes alive
> > mysql -uroot -h127.0.0.1 -P3307 -s < $PROJECT_ROOT/tests/suites/0_stateless/09_0003_remote_drop_table.sql
> ```
> 
> In my dev box, I got:
> 
> > 1	v1
> > 2	v2
> > t2_1	t2_v1
> > t2_2	t2_v2
> > t2_1	t2_v1
> > t2_2	t2_v2
> 
> What's your result?

@dantengsky 
This is what I got:
```
mysql -uroot -h127.0.0.1 -P3307 -s < tests/suites/0_stateless/09_0003_remote_drop_table.sql
'1'     'v1'
'2'     'v2'
't2_1'  't2_v1'
't2_2'  't2_v2'
't2_1'  't2_v1'
't2_2'  't2_v2'
```

**Comment by drmingdrmer** [comment]
> > these two results only different in single quotes, and those single quotes are removed from
> 
> Yes, because single quotes are removed during inseration, and strings will out displayed with quotes by default.
> 
> I think it's the reason for different `datafuse-query` and `datafuse-store` ?
> Maybe your `datafuse-query` is not up to date.

Right. The binary name changed. `kill datafuse-store` did kill the old running store.
