### ISSUE TITLE
[improvement] SUBSTRING(string, start, length)

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1570]
**Summary**

Datafuse has support `SUBSTRING(string FROM start FOR length)`, for example:
```
mysql> select substring('bohu' from 0 for 2);
+-----------------------+
| substring(bohu, 0, 2) |
+-----------------------+
| bo                    |
+-----------------------+
1 row in set (0.02 sec)

```

It's simple for user to support `SUBSTRING(string, start, length)`.
Reference:
https://www.w3schools.com/sql/func_mysql_substring.asp

**Comment by tangwz** [comment]
May I have a try?

**Comment by BohuTANG** [comment]
> May I have a try?

Tips:
comment as follows will take the issue:
`/assignme`

**Comment by tangwz** [comment]
> > May I have a try?
> 
> Tips:
> comment as follows will take the issue:
> `/assignme`

Thanks.As a newbee, I think It may take me a little longer, I will try my best.

**Comment by BohuTANG** [comment]
A Helpful Guide:
https://datafuse.rs/development/contributing/

**Comment by tangwz** [comment]
> A Helpful Guide:
> https://datafuse.rs/development/contributing/

I think I should modify sqlparser-rs first?

**Comment by sundy-li** [comment]
> I think I should modify sqlparser-rs first?

Yes, https://github.com/datafuse-extras/sqlparser-rs/blob/main/src/parser.rs#L648-L665

**Comment by tangwz** [comment]
@sundy-li PTAL.

**Comment by sundy-li** [comment]
@tangwz  Now we can update the version of `sqlparser-rs` in Datafuse and introduce this function styles.
