### ISSUE TITLE
[DOC] add `SHOW TABLES FROM` to document website

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1572]
**Summary**

After https://github.com/datafuselabs/datafuse/pull/1555, Datafuse supports:
```
CREATE TABLE `ss`.`table_1`(id varchar(200));
SHOW TABLES FROM `ss`;
SHOW TABLES IN `ss`;
```

It's time to add them to the website https://datafuse.rs
Reference: https://github.com/datafuselabs/datafuse/pull/1541

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by Patil2099** [comment]
I think it is already there on the website.
