### ISSUE TITLE
The dependence `arrow2` is old

### ISSUE THREAD

**Issue by jackwener** [datafuselabs/datafuse#1573]
**Summary**

Maybe we should dump arrow2. The dependence `arrow2` is old and should be upgraded into `v0.3.0`.

**Comment by jackwener** [comment]
arrow2@v0.3.0 add some useful feature.

**Comment by BohuTANG** [comment]
cc @sundy-li

**Comment by sundy-li** [comment]
OK,  https://github.com/datafuse-extras/arrow2 will fetch upstream in time.

**Comment by jackwener** [comment]
It's not enough because the high-version library isn't compatible with old-version. We need modify many code.

**Comment by sundy-li** [comment]
> It's not enough because the high-version library isn't compatible with old-version. We need modify many code.
Yes, seems lots of codes should be modified.

**Comment by jorgecarleitao** [comment]
The summary of changes from 0.2 to 0.3 is here: https://github.com/jorgecarleitao/arrow2/releases/tag/v0.3.0

Let me know if you need help.

**Comment by sundy-li** [comment]
> The summary of changes from 0.2 to 0.3 is here: https://github.com/jorgecarleitao/arrow2/releases/tag/v0.3.0
> 
> Let me know if you need help.

@jorgecarleitao  Thanks, most of the changes to modify is due to  `Scalar` API, I'll try to create convert from `dyn Scalar` into our own enum `DataValue`, or to replace enum datavalue into arrow2's Scalar trait.

**Comment by jorgecarleitao** [comment]
you can always use `let scalar = scalar.as_any().downcast_ref::<PrimitiveScalar<TYPE>().unwrap()` followed by `scalar.value()` and `scalar.is_valid()` to get the inner and ignore the API.

**Comment by sundy-li** [comment]
@jorgecarleitao  I have submitted a pr in #1575, found a bug in the new version, may you have a look at that?
