### ISSUE TITLE
Unify Catalog API methods to Async Style

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/datafuse#1596]
**Summary**

Unify Catalog API methods to async, remove the internal `block_on` workaround. 

- Background

  > No offense, I am wondering why all read funcs in the trait `Catalog` are not asyncs, observing that there are several `do_block`s in the implementation.

  _Originally posted by @zhongzc in https://github.com/datafuselabs/datafuse/issues/1212#issuecomment-904745955_

**Comment by BohuTANG** [comment]
Let me have a try.

**Comment by dantengsky** [comment]
Thanks bro

**Comment by BohuTANG** [comment]
I have try and found lots of codes need change to async, so thinking a question: what the benefit of changing to async is?
At present, it is better to keep it as it is 😢 
cc: @dantengsky

**Comment by dantengsky** [comment]
yes, lots of code  involved, let's postpone this issue

**Comment by dantengsky** [comment]
May I leave this issue open?

**Comment by BohuTANG** [comment]
> May I leave this issue open?

Sure

**Comment by leiysky** [comment]
@BohuTANG @dantengsky 

I have some concern on this. 

According to my experience, the most usage of catalog is in optimizer, which is canonically synchronous component. Thus I have to rewrite the code into asynchronous or do `block_on` by myself.

So maybe it's better to provide only synchronous API in `Catalog` trait?

**Comment by BohuTANG** [comment]
> @BohuTANG @dantengsky
> 
> I have some concern on this.
> 
> According to my experience, the most usage of catalog is in optimizer, which is canonically synchronous component. Thus I have to rewrite the code into asynchronous or do `block_on` by myself.
> 
> So maybe it's better to provide only synchronous API in `Catalog` trait?

For catalog, sync is more make sense here.
@dantengsky what do you think?

**Comment by dantengsky** [comment]
I am not sure about it.

On the one hand, the Catalog is backed by flight service(for the time being) which is async, thus it is easier/more natural for Catalog API to go with async style.

On the other hand:
- if the optimizer depends on Catalog heavily while searching for better plans (correct me if I am mistaken), it would be better to make catalog API sync.
- Since nothing prevents us from encapsulating an async service as sync APIs, and with cache enabled, we may have bot efficient impls and elegant APIs.
 
Also, It may depend on the way we provide statistical information to the optimizer (again, correct me if I am mistaken). for the time being, as we discussed before, I am considering embedding statistics into the table metadata, which is NOT directly embedded in the MetaStore, but saved in object storage.  Maybe the optimizer should consult the index layer while planning.  I mean, the extended/enhanced index layer, which can provide table statistics (min, max, cardinality, row num, size, etc).

**Comment by dantengsky** [comment]
please allow me to transform this issue into a discussion
