### ISSUE TITLE
Maybe rename `DataType::Utf8` to a more reasonable name?

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/datafuse#1601]
Seems this name came from `LargeUtf8` in arrow.

It looks a little bit weird since in databases like Postgres or MySQL **collation** and **charset** are seperated from **types**. In this case, `CHAR`(string) is a data type and `utf8` is a charset.

We can only support utf8 charset for now, but IMO maybe it's more reasonable to rename `DataType::Utf8` to `String` or `StringUtf8`?

**Comment by leiysky** [comment]
cc @sundy-li

**Comment by sundy-li** [comment]
Maybe remove `DataTye::Utf8` and let's keep `DataType::Binary` as `DataType::String`, this could support more charset datatypes.

**Comment by leiysky** [comment]
@sundy-li It seems there has been many macros and utility of both `DataType::Utf8` and `DataType::Binary`, do you have any idea about how to deal with them?

**Comment by sundy-li** [comment]
Let's do it in #1603

**Comment by leiysky** [comment]
Duplicated with #1603
