### ISSUE TITLE
Add priority to cluster node

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#163]
**Summary**
If the CPU is ARM or other low CPU model,  priority can reduce tasks assigned.

**Comment by jyizheng** [comment]
Do you mean Arm CPU should have low priority than Intel CPU? Which file should be changed to implement this?

**Comment by BohuTANG** [comment]
It's on the plan.
1. Add priority(interge) to the cluster node struct: https://github.com/datafuselabs/fuse-query/blob/ad032c5ebe9a2859b340b822ee0ba8c1a1f8910c/src/clusters/node.rs#L6

2. Redistribution of partitions based on the priority, (the current logic is that all nodes are equally)
https://github.com/datafuselabs/fuse-query/blob/ad032c5ebe9a2859b340b822ee0ba8c1a1f8910c/src/planners/plan_scheduler.rs#L18

**Comment by jyizheng** [comment]
The third link is no longer valid. It should be below.

https://github.com/datafuselabs/datafuse/blob/6d2524a01f25ebbd8b59d9794e9894f70d502954/query/src/rpcs/http/v1/cluster.rs#L34

**Comment by jyizheng** [comment]
I am happy to work on this task

**Comment by jyizheng** [comment]
Closed by #194

**Comment by sundy-li** [comment]
You can use `closes #163` in that pr.
