### ISSUE TITLE
[feature] system.configs table

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1630]
**Summary**

Add system.configs table to show the configs:
columns:
`name | value | group | description`

```
 select * from system.configs;

┌─name──────────────────┬─value─────┬─group─────────┬─description──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ num_cpus              │ 10        │ Query         │ Maximum thread to use for the query                                                                                                  │
└───────────────────────┴───────────┴───────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Reference:
system.settings table:
https://github.com/datafuselabs/datafuse/blob/master/query/src/datasources/system/settings_table.rs

**Comment by GrapeBaBa** [comment]
what neeed to do for this task?

**Comment by BohuTANG** [comment]
> what neeed to do for this task?

Add a system `configs` table can be queried.
There are many system tables there for reference:
https://github.com/datafuselabs/datafuse/blob/master/query/src/datasources/system/

**Comment by GrapeBaBa** [comment]
We need iterate all the attribute names in several config structs, right?

**Comment by BohuTANG** [comment]
> We need iterate all the attribute names in several config structs, right?

That is true

**Comment by GrapeBaBa** [comment]
I feel I can write a procedural macros to make config struct to a hashmap. Which crate is suite for write this macro?

**Comment by BohuTANG** [comment]
@GrapeBaBa 
This may be helpful https://crates.io/crates/field_types

**Comment by BohuTANG** [comment]
Or may iter the serde_json Value to get the filed and value, something like:
```
   pub fn configs_to_map(&self) -> Result<(...)> {
        let str = serde_json::to_string(self)?;
        let values: Vec<serde_json::Value> = serde_json::from_str(str.as_str())?;
        for v in values.into_iter() {
            log::info!("{:?}", v);
        }
        Ok(())
    }
```

**Comment by GrapeBaBa** [comment]
> @GrapeBaBa
> This may be helpful https://crates.io/crates/field_types

This lib is not quite good, it cannot get the attribute name dynamic.

**Comment by GrapeBaBa** [comment]
> Or may iter the serde_json Value to get the filed and value, something like:
> 
> ```
>    pub fn configs_to_map(&self) -> Result<(...)> {
>         let str = serde_json::to_string(self)?;
>         let values: Vec<serde_json::Value> = serde_json::from_str(str.as_str())?;
>         for v in values.into_iter() {
>             log::info!("{:?}", v);
>         }
>         Ok(())
>     }
> ```

Ok, let me see.

**Comment by GrapeBaBa** [comment]
it works. Another question is how can I get description value for every config?

**Comment by BohuTANG** [comment]
> it works. Another question is how can I get description value for every config?

It seems like a `StructOpt` problem to get his `help`.

**Comment by GrapeBaBa** [comment]
> StructOpt

Yes, I see it. But how to extract this `help`?

**Comment by BohuTANG** [comment]
@GrapeBaBa Hi!
Maybe we can keep the `description` column as empty.
