### ISSUE TITLE
[improvement] remove unused `common/store-api/session_api.rs`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1639]
**Summary**

`common/store-api/session_api.rs` and `flights/src/impls/session_api_impl.rs` not used anymore, we should remove it.

**Comment by jyz0309** [comment]
The `KillQueryReq` still in use. Should I move it to other place? If so, where you think is better.

**Comment by BohuTANG** [comment]
If the KillQueryReq and related is not used anymore, we can also remove it :)

**Comment by BohuTANG** [comment]
If the KillQueryReq and related is not used anymore, we can also remove it :)
