### ISSUE TITLE
[CI] make the log level from `INFO` to `ERROR`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1687]
**Summary**

In https://github.com/datafuselabs/datafuse/tree/master/scripts/ci, the store default log level is INFO.
It's a bit mesh for the stateless test CI, so we consider change them to `ERROR`

**Comment by jyz0309** [comment]
Sry, but I find that the log level is ERROR? https://github.com/datafuselabs/datafuse/blob/f0fa13a31645f68a8a6c1e7592877f079d044812/scripts/deploy/config/datafuse-query-node-3.toml#L5

**Comment by BohuTANG** [comment]
> Sry, but I find that the log level is ERROR?
> 
> https://github.com/datafuselabs/datafuse/blob/f0fa13a31645f68a8a6c1e7592877f079d044812/scripts/deploy/config/datafuse-query-node-3.toml#L5

Sorry, it's the store not the query.
I have a patch to fix it:
https://github.com/datafuselabs/datafuse/pull/1697
