### ISSUE TITLE
[feature] add username for the remote database(question)

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1692]
**Summary**

Since the MetaStore is a multi-tenat service, if we have a user(`jack`) login in from the MySQL client and run:
mysql> show databases;

This command will:
1. get the local databases
2. get the remote databases from the store backend

For S2, how the backend store returns `jack` databases information?

**Comment by BohuTANG** [comment]
CC: @dantengsky @drmingdrmer 

Perhaps your guys could answer it

**Comment by dantengsky** [comment]
is `jack` one of the users of a tenant? or `jack` is a tenant?

IMO:

if `jack` is a tenant, that would be easier, since database meta belongs to a specific tenant.

if `jack` is a user of a tenant....  well, that is another (long) story.   There should be other metadata for user credential/role/privilege...,  which may be stored inside the backend store or not (depends on serval things, e.g. security, integration...).

**Comment by drmingdrmer** [comment]
It is possible to maintain the tenant-user-database relationship in metastore in a tree-like data structure, with some reversed index.

Or just dump these data into a static file that is saved in DFS.
And meta store just maintains the linearizability of the updates to it, by versioning every change to it.
Just like the way fuse-query does for table indexes.

**Comment by BohuTANG** [comment]
In the datafuse(data panel), all the user is normal user, not tenant, we can get the databases by the user name(or id).
In the control panel, the tenant may have many users, it feels like a user management system, expressed in our metastore :)

**Comment by zhang2014** [comment]
tenants are managed by Datafuse cli and users are managed by Datafuse query(maybe the tenant is just a prefix in config), maybe they shouldn't be relevant(this is my understanding. maybe it's wrong)?

**Comment by BohuTANG** [comment]
> tenants are managed by Datafuse cli and users are managed by Datafuse query(maybe the tenant is just a prefix in config), maybe they shouldn't be relevant(this is my understanding. maybe it's wrong)?

That's true.
