### ISSUE TITLE
[feature] add `tenant` config to QueryConfig group

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1724]
**Summary**

add `tenant` config to QueryConfig group for tenant identifier.

**Comment by BohuTANG** [comment]
@jyz0309 Hi,

This issue is one part of https://github.com/datafuselabs/datafuse/issues/1700, so I take it away here :)

**Comment by jyz0309** [comment]
> @jyz0309 Hi,
> 
> This issue is one part of #1700, so I take it away here :)

Ok, I take it just because [#1723 ](https://github.com/datafuselabs/datafuse/issues/1723) need it:)
