### ISSUE TITLE
The document in `ArrayAgg` is not same with its impls.

### ISSUE THREAD

**Issue by yjhmelody** [datafuselabs/datafuse#1741]
**Summary**

For Example `sum`:

```rust
    /// Aggregate the sum of the ChunkedArray.
    /// Returns `DataValue::Null` if the array is empty or only contains null values.
    fn sum(&self) -> Result<DataValue> {
        Err(ErrorCode::BadDataValueType(format!(
            "Sum operation not supported for {:?}",
            self,
        )))
    }
```

But `sum` in `DFBooleanArray` return Boolean if `is_empty` or `all_is_null`
```rust
impl ArrayAgg for DFBooleanArray {
    fn sum(&self) -> Result<DataValue> {
        if self.all_is_null() {
            return Ok(DataValue::Boolean(None));
        }
        let sum = self.into_iter().fold(0, |acc: u64, x| match x {
            Some(v) => acc + v as u64,
            None => acc,
        });

        Ok(sum.into())
    }
...
}
```

But for `sum` I think it is more reasonable return `0`. 

The document descriptions of other aggregate functions have similar problems
I think the description of most documents are more reasonable than the implementations.

**Comment by sundy-li** [comment]
> But for sum I think it is more reasonable return 0

But It's MySQL style, I do prefer to make it return 0 too.

And yes, the document is wrong, would you make a pr to fix this?
