### ISSUE TITLE
Add projection push down

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#222]
**Summary**

Add  projection push down to remove unused columns.
If the table  schema is:
```
create table t1{
a int,
b int,
c int,
}
```
Query `select a from t1 where c=1` plan only requeird the column `a and c`

**Comment by jyizheng** [comment]
I am happy to work on this

**Comment by jyizheng** [comment]
#286  is ready for review. @BohuTANG

**Comment by BohuTANG** [comment]
> #286 is ready for review. @BohuTANG

Great, I will do a review today.

**Comment by jyizheng** [comment]
@BohuTANG @zhang2014 , could you please review PR 286 to see if it is okay to be merged?

**Comment by jyizheng** [comment]
This issue can be closed.
