### ISSUE TITLE
CTE is not supported, but fuse reports internal("Unknown database: \'default\'")

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/datafuse#27]
mysql> with t as ( select sum(number)n from system.numbers_mt(1000))select * from t;
ERROR 1105 (HY000): Internal("Unknown database: \'default\'")

**Comment by tlightsky** [comment]
CTE is very useful for complex query,
should support it in future

**Comment by BohuTANG** [comment]
it's time to start it, let's go it in another new CTE issue
