### ISSUE TITLE
Group by: Unable to get alias field named 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#317]
**Describe the bug**

https://github.com/datafuselabs/datafuse/pull/313#issuecomment-820255707

wrong group by behavior

1. number % 3 is not an aggregate function, expect to get an error. (move to #404 )
```
datafuse :)  select  number % 3 as d  ,  avg(number) d  from numbers(1000) group by  number % 4 ;

SELECT
    number % 3 AS d,
    avg(number) AS d
FROM numbers(1000)
GROUP BY number % 4

Query id: d6ea17ae-4ca3-4c5a-af28-e210e871e273

┌─d─┬───d─┐
│ 0 │ 501 │
│ 1 │ 498 │
│ 2 │ 500 │
│ 1 │ 499 │
└───┴─────┘

4 rows in set. Elapsed: 0.004 sec.
```

2. alias not working for group by(fixed in #384 )
```
datafuse :)  select number % 3 as d,  avg(number) d  from numbers(1000) group by d;

SELECT
    number % 3 AS d,
    avg(number) AS d
FROM numbers(1000)
GROUP BY d

Query id: 84abe75d-cd9b-4142-be27-52fbe3b31615


Received exception from server (version 19.17.1):
Code: 101. DB::Exception: Received from 127.0.0.1:9000. . Other error: `Execute error: Invalid argument error: Unable to get field named "d". Valid fields: ["number"]
```

**Comment by jyizheng** [comment]
I am interested in these two problems. 

For 1,  do we want to add some checks for `aggr_expr`  here: https://github.com/datafuselabs/datafuse/blob/9b6cc3df103eb16273a9aca3b8ee73e06a1bee38/common/planners/src/plan_builder.rs#L100

**Comment by BohuTANG** [comment]
Yes, it would be better to do as arrow-datafusion does.
Now, we get all expression type&names from the function, they can get from expression plan directly.

**Comment by jyizheng** [comment]
@BohuTANG  Which code for datafusion is relevant to this problem?

**Comment by BohuTANG** [comment]
https://github.com/apache/arrow-datafusion/blob/57eeb64659b9ca9c496a959f7716090fb32085b6/datafusion/src/logical_plan/builder.rs#L295

and to_field 
https://github.com/apache/arrow-datafusion/blob/57eeb64659b9ca9c496a959f7716090fb32085b6/datafusion/src/logical_plan/expr.rs#L347

**Comment by BohuTANG** [comment]
The easy way to do group by alias is to add one optimizer rule(like group_by_push_down):
`select number as a, number%3 as b from numbers_mt(10) group by a,b`
to
`select number as a, number as b from numbers_mt(10) group by number,number%3`

**Comment by jyizheng** [comment]
Does PR 384 also fix 1?

**Comment by BohuTANG** [comment]
> Does PR 384 also fix 1?

It plan to fixed in another pr, aggr expression valid check.

**Comment by jyizheng** [comment]
Are you going to work on the PR of aggr expression valid check?

**Comment by BohuTANG** [comment]
Not yet

**Comment by jyizheng** [comment]
datafusion has physical plan which defines AggregateFunction. Is this what we need to fix 1? 

https://github.com/apache/arrow-datafusion/blob/9a1e7c741a3589e7ddeff87ca0a420dc55436a35/datafusion/src/physical_plan/aggregates.rs#L52

**Comment by BohuTANG** [comment]
We have aggregatation functions.
To fix 1 need a check like:
https://github.com/apache/arrow-datafusion/blob/9a1e7c741a3589e7ddeff87ca0a420dc55436a35/datafusion/src/sql/planner.rs#L701

**Comment by BohuTANG** [comment]
2 is fixed.
1 move to #404
