### ISSUE TITLE
[edit] What is ClickHouse MergeTree disk structure

### ISSUE THREAD

**Issue by Sallery-X** [datafuselabs/datafuse#398]
Make sure to check documentation https://datafuse.dev first.

**Comment by BohuTANG** [comment]
MergeTree is not a table format, it's general `an idea` of data organization.
So for a table storage engine, we have two parts:
1. table format: we use some Iceberge-like to arxiv snapshot
2. data organization: we use parquet-like to do the data store in the file

BTW, engine type(Parquet or ClickHouse-like) is optional.
Feel free to follow our fusestore documentation(RFC):
https://github.com/datafuselabs/datafuse/blob/master/docs/rfcs/store/2021-04-22-store-design.md

**Comment by Sallery-X** [comment]
> MergeTree is not a table format, it's general `an idea` of data organization.
> So for a table storage engine, we have two parts:
> 
> 1. table format: we use some Iceberge-like to arxiv snapshot
> 2. data organization: we use parquet-like to do the data store in the file
> 
> BTW, engine type(Parquet or ClickHouse-like) is optional.
> Feel free to follow our fusestore documentation(RFC):
> https://github.com/datafuselabs/datafuse/blob/master/docs/rfcs/store/2021-04-22-store-design.md

我理解你们数据内存，数据交换，数据存储，都用了arrow格式，是这样么？clickhouse内部是什么结构呢

**Comment by BohuTANG** [comment]
It's a bit hard to explain the MergeTree underlying, but there is a blog to helpful:
https://bohutang.me/2020/06/26/clickhouse-and-friends-merge-tree-disk-layout/
