### ISSUE TITLE
projection expression if not in group by expression return error

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#404]
**Describe the bug**

https://github.com/datafuselabs/datafuse/pull/313#issuecomment-820255707

wrong group by behavior, expect to get an error.
```
datafuse :)  select  number % 3 as d  ,  avg(number) d  from numbers(1000) group by  number % 4 ;

SELECT
    number % 3 AS d,
    avg(number) AS d
FROM numbers(1000)
GROUP BY number % 4

Query id: d6ea17ae-4ca3-4c5a-af28-e210e871e273

┌─d─┬───d─┐
│ 0 │ 501 │
│ 1 │ 498 │
│ 2 │ 500 │
│ 1 │ 499 │
└───┴─────┘

4 rows in set. Elapsed: 0.004 sec.
```

**Comment by jyizheng** [comment]
BTW, I am working on a PR for this.

**Comment by jyizheng** [comment]
@BohuTANG  With aggregate expression check, there are 4 unit tests that cannot pass.

Should we change these unit tests? Also, what error code should be returned if the aggregate expressions fail to pass this check?

**Comment by BohuTANG** [comment]
> @BohuTANG With aggregate expression check, there are 4 unit tests that cannot pass.
> 
> Should we change these unit tests? Also, what error code should be returned if the aggregate expressions fail to pass this check?

1) If the result is by design, change it.
2) return the error, https://github.com/datafuselabs/datafuse/pull/362 will normalize the error code for us

**Comment by jyizheng** [comment]
All the tests that failed have been changed. PR 405 is ready for review.

**Comment by jyizheng** [comment]
For the statement below: ` select  number % 3 as d  ,  avg(number) d  from numbers(1000) group by  number % 4 ;`

If we change it to ` select  number % 3 as d  ,  avg(number) d  from numbers(1000) group by  number % 3 ;`,  the new one is also valid, correct?

**Comment by BohuTANG** [comment]
> For the statement below: ` select number % 3 as d , avg(number) d from numbers(1000) group by number % 4 ;`
> 
> If we change it to ` select number % 3 as d , avg(number) d from numbers(1000) group by number % 3 ;`, the new one is also valid, correct?

yes, it's by design. 
Alias can not be duplicated.
By the way, we can install a ClickHouse server locally, and check it how did, it would be more helpful.

**Comment by jyizheng** [comment]
Got it. Will do. It is in my plan to install clickhouse locally.

**Comment by sundy-li** [comment]
Already fixed in master, closing.
