### ISSUE TITLE
Support distinct

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#430]
**Summary**

```
select count(distinct number) from (select number%3 as number from numbers_mt(100));
```

**Comment by BohuTANG** [comment]
@sundy-li 

Do we also need to support other `distinct`?
Such `sumDistinct`, if need I am happy to open an issue

**Comment by sundy-li** [comment]
> @sundy-li
> 
> Do we also need to support other `distinct`?
> Such `sumDistinct`, if need I am happy to open an issue

Ok, though it's not MySQL style,  but it's better than nothing.  I'll try to implement a generic combinator for AggregateFunction, such as `sumIf, sumDistinct`

**Comment by BohuTANG** [comment]
Sound interesting.
For functions, as long as they are helpful to the user, we should have them(MySQL's style function may not work well for analytics)!
BTW, I have add a functiuon track issue here https://github.com/datafuselabs/datafuse/issues/758

**Comment by BohuTANG** [comment]
FYI, all the tracks also in Roadmap: https://github.com/datafuselabs/datafuse/issues/746
