### ISSUE TITLE
Optimizer: constant folding for comparison expression

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#433]
**Summary**

Like arrow-datafusion does in [constant_folding.rs](https://github.com/apache/arrow-datafusion/blob/f43dc444eb510f0ff170adecb5a23afb39c489a8/datafusion/src/optimizer/constant_folding.rs):

`expr = true` and `expr != false` to `expr` when `expr` is of boolean type
`expr = false` and `expr != true` to `!expr` when `expr` is of boolean type
`true = true` and `false = false` to `true`
`false = true` and `true = false` to `false`
`!!expr` to `expr`
 `expr = null` and `expr != null` to `null`

**Comment by jyizheng** [comment]
Could you assign this task to me? @BohuTANG

**Comment by BohuTANG** [comment]
@jyizheng 

you can comments as:
/assignme
