### ISSUE TITLE
optimizer use name to relation field have problem

### ISSUE THREAD

**Issue by tomjiang1987** [datafuselabs/datafuse#434]
Hi,
I have read some optimizer code, the optimizer use name to relation between columns,
This implementation is problematic. In my experience, neither calcite nor tidb using this method. 

and also find some issue related
https://github.com/apache/arrow-datafusion/issues/155

**Comment by BohuTANG** [comment]
Thanks for the professional reminder.
This problem will probably be fixed when we do join (start soon).
