### ISSUE TITLE
Support optimizer for having

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#458]
**Summary**

Support optimizer for having

**Comment by tlightsky** [comment]
does this mean make some changes around [here](https://github.com/datafuselabs/datafuse/blob/36c9396f6c67e9125614964380177d7f9a55597a/fusequery/query/src/optimizers/optimizer_filter_push_down.rs#L37-L37)

**Comment by BohuTANG** [comment]
It is mainly about alias rewrite like: https://github.com/datafuselabs/datafuse/blob/master/fusequery/query/src/optimizers/optimizer_alias_push_down.rs#L40

**Comment by BohuTANG** [comment]
This is not an issue now.
