### ISSUE TITLE
Invalid argument error: Unable to get field named "c1". Valid fields: ["number"]

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#460]
**Summary**

```
mysql> select number as c1 from numbers_mt(19) where  number>10 order by c1;
ERROR 1105 (HY000): Code: 1002, displayText = Invalid argument error: Unable to get field named "c1". Valid fields: ["number"].
```
Order by need alias push down.

It looks like we need to abstract out an optimizer rule, such as alias push down, for filter/groupby/orderby all.
Currently, all alias push down logic is mixed in each rules.

**Comment by jyizheng** [comment]
The statement works on clickohuse.
`
ClickHouse client version 21.4.5.46 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.4.5 revision 54447.

bunsen1.telenet.unc.edu :) select number as c1 from numbers_mt(19) where  number>10 order by c1

SELECT number AS c1
FROM numbers_mt(19)
WHERE number > 10
ORDER BY c1 ASC

Query id: 28d82ebe-db77-4bb9-a5aa-78006029b5e8

┌─c1─┐
│ 11 │
│ 12 │
│ 13 │
│ 14 │
│ 15 │
│ 16 │
│ 17 │
│ 18 │
└────┘

8 rows in set. Elapsed: 0.002 sec. 
`

**Comment by BohuTANG** [comment]
This is by design, here is bug in datafuse.
For alias expression push down, we need an rule to do that, it looks more clearly and simple.

**Comment by jyizheng** [comment]
This only happens for the branch of PR 405, right? Does the current master also have this problem?

**Comment by BohuTANG** [comment]
> This only happens for the branch of PR 405, right? Does the current master also have this problem?

Not only PR#405 but for all barnch.
We don't handle the alias in order by expression.

**Comment by jyizheng** [comment]
I see. I am happy to work on this since PR 405 depends on this.
