### ISSUE TITLE
Throw exceptions when using AggregatorFunction as argument inside  AggregatorFunction

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#486]
**Describe the bug**

```
select min(sum(number)) from numbers(10);

SELECT min(sum(number))
FROM numbers(10)

0
```

It returns 0, because `eval` function in AggregatorSum is wrong!

https://github.com/datafuselabs/datafuse/blob/e21145fb1e66efa33f37e1490f212709079875ae/common/functions/src/aggregators/aggregator_sum.rs#L62-L64

**Expected behavior**

Throw exceptions.  http://sqlfiddle.com/#!9/c64624/8

**Comment by BohuTANG** [comment]
@jyizheng 

This check could probably be done in this pr:
https://github.com/datafuselabs/datafuse/pull/542

**Comment by jyizheng** [comment]
> @jyizheng
> 
> This check could probably be done in this pr:
> #542

Sure. Happy to do it.
