### ISSUE TITLE
[query] Make the hash vectorized

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#520]
# Summary

Currently, the approach hash group by aggregates is to create a key  from the row values in:
https://github.com/datafuselabs/datafuse/blob/b89b42e6f08c3036c29cc9284f3e849c93677e91/fusequery/query/src/pipelines/transforms/transform_groupby_partial.rs#L148

It better to make the hash in vectorized way, this is a common crate that can be used by both query and store.

Reference:
https://www.cockroachlabs.com/blog/vectorized-hash-joiner/
https://github.com/apache/arrow/commit/e073d8cbfafc881f0991e9001af973163951e3c1

**Comment by BohuTANG** [comment]
We can calculate the column hash after GroupBy ExpressionAction, it's vectorized.
For example:
SELECT max(number) FROM numbers_mt(10000000) GROUP BY number%3, number%3;

For a block it will do:
1. ExpressionAction: number%3
2. ExpressionAction: number%2

block schema:
```| number | number%3 | number%3 |```

To be vectorized we add  two additional actions:
1. ExpressionAction:  hash(number%3)
2. ExpressionAction:  hash(number%2)

block schema:
```| number | number%3 | number%3 | hash(number%3) | hash(number%2) |```

And we only concat the two hash to one row.

**Comment by sundy-li** [comment]
http://myeyesareblind.com/2017/02/06/Combine-hash-values/

**Comment by BohuTANG** [comment]
> http://myeyesareblind.com/2017/02/06/Combine-hash-values/

Hash each key seems a good idea, not sure how ClickHouse did, need to dig it.
