### ISSUE TITLE
SUBSTRING: Unsupported expression: - 3

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#573]
**Describe the bug**
```
mysql> SELECT SUBSTRING('1234567890' FROM -3 FOR 3);
ERROR 1105 (HY000): Code: 5, displayText = Unsupported expression: - 3, type: UnaryOp { op: Minus, expr: Value(Number("3", false)) }.
```

expect:
```
+--------------------------------+
| SUBSTRING('1234567890', -3, 3) |
+--------------------------------+
| 890                            |
+--------------------------------+
```

**Comment by tlightsky** [comment]
to support this feature, 
it seems we need to support `UnaryOp` in arithmetic first

**Comment by JmPotato** [comment]
@BohuTANG @tlightsky I'd like to take this task, could you please give me some instructions? I took a quick look at the existing code, it seems that there are several sub-tasks:

* Support `UnaryOp` in the parser.
* Support the expression in the planner.
* ...

Before some hints are given, I will keep exploring. Thanks!
