### ISSUE TITLE
Alias push down optimization seems to be logically wrong

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/datafuse#574]
Reference to the comment:
https://github.com/datafuselabs/datafuse/blob/65590e8b52e68f63726c8e6579eec7657a725c7d/common/planners/src/plan_rewriter.rs#L160-L163

In this case, the variable `b` in `WHERE` clause indicates a column named `b` but not alias of `a`, since projection is at the top of a query block.

Here's output of Postgres 13 and MySQL 8.0.

Postgres:
![image](https://user-images.githubusercontent.com/22445410/118670257-0612d700-b829-11eb-869c-05f34a0ff744.png)

MySQL:
![image](https://user-images.githubusercontent.com/22445410/118670308-12972f80-b829-11eb-9545-1dac2ce5f664.png)

**Comment by leiysky** [comment]
@BohuTANG PTAL

**Comment by sundy-li** [comment]
Yes, currently implementation is kind of like clickhouse style, maybe it's wrong.

**Comment by leiysky** [comment]
I think we can disable the `AliasPushDown` optimization, so I can finish #563 without refactoring `optimizer_alias_push_down.rs` 🤣

**Comment by sundy-li** [comment]
Ok, you can disable it.  I will refactor this in #550 ,  I do not think Alias is an optimization. I'll rewrite aliases during the planner building stage.

**Comment by leiysky** [comment]
> Ok, you can disable it. I will refactor this in #550 , I do not think Alias is an optimization. I'll rewrite aliases during the planner building stage. But if you disable that, there will be some tests that fail to pass...

This makes sense. I'll deal with the test cases either.
