### ISSUE TITLE
[common/exception] simplify ErrorCodes with trait `From<xxx>`

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#577]
**Description**

impl `From` for `ErrorCodes`, e.g., `impl From<anyhow::Error> for ErrorCodes` so that in most cases we do not need to use a type-specific conversion explicitly, e.g., `ErrorCodes::from_anyhow()`. But instead, using a universal form `ErrorCode::from()` is quite enough.

Furthermore, when type inference is possible, we could just totally remove the conversion statement, e.g.:
`fetch_impl(flight_data, &schema).map_err(ErrorCodes::from_anyhow)` to `fetch_impl(flight_data, &schema)`

**Comment by zhang2014** [comment]
@drmingdrmer Great idea, but for now `from_arrow`, `from_anyhow` function is mainly used to find codes that need to be refactor. I think we should implement it better after #440 closed.

**Comment by drmingdrmer** [comment]
@zhang2014 If you'd refine all the conversion from `arrow::Error` to `ErrorCodes`, just rewrite the `From` trait implementation.
If you'd customize every single arrow::Error to `ErrorCodes` conversion(unlikely necessary IMHO), just temporarily remove the `From<array::Error>` then you have a list where it is used when building.

Thus I see no trouble applying this patch before #440 .

So, how about closing an issue ASAP.

**Comment by zhang2014** [comment]
> @zhang2014 If you'd refine all the conversion from arrow::Error to ErrorCodes, just rewrite the From trait implementation.
If you'd customize every single arrow::Error to ErrorCodes conversion(unlikely necessary IMHO), just temporarily remove the From<array::Error> then you have a list where it is used when building.
> 
> Thus I see no trouble applying this patch before #440 .
> 
> So, how about closing an issue ASAP.

Great! , we can continue #580
