### ISSUE TITLE
[good first issue] remove unnecessary fake meta data

### ISSUE THREAD

**Issue by hulunbier** [datafuselabs/datafuse#581]
https://github.com/datafuselabs/datafuse/blob/f9d23d7efc1c0077d764891bf2ea02070742f4b4/fusequery/query/src/sql/plan_parser.rs#L175-L182

Upstream(arrow-rs) has fixed the related issue, we no longer need to provide non-empty meta (to ensure schema's deserialization goes well).

Please constructs the `schema` by utilizing [`SchemaRefExt::create`](https://github.com/datafuselabs/datafuse/blob/master/common/datavalues/src/data_schema.rs#L16) or something equvilant.

**Comment by BohuTANG** [comment]
Now we have SchemaRefExt::create in: https://github.com/datafuselabs/datafuse/blob/master/common/datavalues/src/data_schema.rs#L16


But it wraps only Arc now.

**Comment by dantengsky** [comment]
> Now we have SchemaRefExt::create in: https://github.com/datafuselabs/datafuse/blob/master/common/datavalues/src/data_schema.rs#L16
> 
> But it only wraps Arc now.

oops, u r right. We should not simply remove all those lines. Let me modify the issue description.
BTW, would you pls label this issue as "good-first-issue", so that newcomers may find some easy tasks quickly?

**Comment by BohuTANG** [comment]
Yes, it's a welcome bot and some guideline links for the first contributor, fun
