### ISSUE TITLE
Shall we turn on GitHub Discussion for open-ended discussion?

### ISSUE THREAD

**Issue by tisonkun** [datafuselabs/datafuse#608]
I found this project interesting and want to see what I can do for its RoadMap.

GitHub has a mechanism for this kind of discussion named [GitHub Discussion](https://docs.github.com/en/discussions) and I think it is a common question "What Can I Contribute".

Open-ended discussion, different from concrete issue, is often hard to target a clear scope at the first time. Do you think of turn on GitHub Discussion for for open-ended discussion, like a forum or an old-fashioned mailing list?

> **Background**
>
> I am one of [Apache Flink Committers](http://people.apache.org/phonebook.html?uid=tison) and an [open source program practitioner](https://github.com/github/opensource.guide). I'm willing to help build the community by first participanting development.

cc @BohuTANG

**Comment by BohuTANG** [comment]
Sure, github discussion enabled.
Thanks for your suggestion.

**Comment by tisonkun** [comment]
Thanks! Let me try to create some topics...
