### ISSUE TITLE
Flight error broke tests

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#614]
(you don't have to strictly follow this form)

**Describe the bug**

In `flight_service.rs`, we can find 
```
  // Pipeline.
  let mut pipeline = PipelineBuilder::create(ctx.clone(), plan.clone())
      .build()
      .map_err(|e| Status::internal(e.to_string()))?;

```

So if the pipeline builder got ErrorCodes as return value, the error may be wrapped, and this will break the stateless tests in cluster mode. 

```
-ERROR 1105 (HY000) at line 2: Code: 15, displayText = Action must be non-aggregated function.
+ERROR 1105 (HY000) at line 2: Code: 1002, displayText = status: Internal, message: "Code: 15, displayText = Action must be non-aggregated function.", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 24 May 2021 23:42:55 GMT"} }.

```

**Comment by zhang2014** [comment]
fixes in https://github.com/datafuselabs/datafuse/pull/469/files#diff-e414e357b15378b481f6f47df4eadd9e6221a4d4cc19ba66dcf68881527240abR51
