### ISSUE TITLE
After merging Refactor expressions #550, the performance of aggregate is low.

### ISSUE THREAD

**Issue by lideen999** [datafuselabs/datafuse#619]
#550 
@sundyli

SELECT min(number), max(number),number%3   FROM numbers_mt (100000000)  GROUP BY number%3  ;

**Time consuming comparison**
 Elapsed: 0.873 sec.   VS    Elapsed: 2.043 sec. 

**Before the merger:**

┌─min(number)─┬─max(number)─┬─modulo(number, 3)─┐
│           0 │    99999999 │                 0 │
│           1 │    99999997 │                 1 │
│           2 │    99999998 │                 2 │
└─────────────┴─────────────┴───────────────────┘

3 rows in set. Elapsed: 0.873 sec. Processed 100.00 million rows, 800.72 MB (114.57 million rows/s., 917.42 MB/s.) 

**After the merger:**

┌─min(number)─┬─max(number)─┬─(number % 3)─┐
│           0 │    99999999 │            0 │
│           1 │    99999997 │            1 │
│           2 │    99999998 │            2 │
└─────────────┴─────────────┴──────────────┘

3 rows in set. Elapsed: 2.043 sec. Processed 100.00 million rows, 800.72 MB (48.96 million rows/s., 392.00 MB/s.)

**Comment by sundy-li** [comment]
Thanks for the issue, may need time to improve that.

**Comment by lideen999** [comment]
@sundy-li  perfect ！
