### ISSUE TITLE
Store and Query integration tests

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#628]
**Summary**
Now, some test cases are ready to run with FuseStore and FuseQuery after https://github.com/datafuselabs/datafuse/pull/587
Such as:
1. create database/table
2. simple insert

**Comment by dantengsky** [comment]
Are there any "styles" of the way to organize integration testing that we should follow?

**Comment by BohuTANG** [comment]
Prefere the clickhouse style.
The first version integration test is simple, it's based on stateless test:
1. build fuse-store/fuse-query
2. start fuse-store
3. start fuse-query
4. run some tests whoes database engine is remote

**Comment by dantengsky** [comment]
Got it, thanks
