### ISSUE TITLE
Use sqush and merge for the commit

### ISSUE THREAD

**Issue by JmPotato** [datafuselabs/datafuse#645]
**Description**

I suggest using [squash and merge](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits) as the default way of merging PRs. It's more clear on tracking the commit history and showing the PR info.

**Comment by drmingdrmer** [comment]
You are right. I hate merge too.

For a small project, the best strategy would be rebase-merge or squash-merge, to get a clean linear history.

For a community-driven project, with several long-term development branches, the best merge strategy would be do-not-modify-a-published-branch. Keeping the history helps others to track what is going on.
E.g., somebody hacks something based on your under-developing branch. Then your branch is squashed and merged. Then the poor guy may get a lot of conflicts when merging the upstream master.

Just personal opinion. The decision is up to whether a squash confuses other developers.

**Comment by sundy-li** [comment]
I do agree with that. I  just turn that on!

**Comment by JmPotato** [comment]
> I do agree with that. I  just turn that on! Maybe squash + rebase is better ?
> 
> ![image](https://user-images.githubusercontent.com/3325189/119859286-d447f180-bf47-11eb-8368-7dc204d8c7d5.png)
> 
> 
> 
> 

LGTM. Should we also update the config of bot?

**Comment by BohuTANG** [comment]
Hi, 

`Allow merge commits` used for tracing all the history of the git chain, such as who merged, and tracing by some `robot`
This style is used by Rust and ClickHouse.

**Comment by sunisdown** [comment]
@BohuTANG do we have git commit/pull request guidelines?
I find a lot duplicate commit messages in the history,  which don't provide valuable information but rather make the commit history a bit messy. I totally agree that we need to trace all the history of the git chain, but it would be great if we can `git rebase` and have a cleaner history.

**Comment by BohuTANG** [comment]
@sunisdown 
There is no git guidelines here(It's all in your own style), this makes databend dev workflow very fast(welcome experience).

git chain stone all the git operations makes it easy for everyone to understand what happened in the past, like who merged and where the PR is, based on this git data, we can analyse it someday.
