### ISSUE TITLE
NOT expression bug

### ISSUE THREAD

**Issue by jyizheng** [datafuselabs/datafuse#646]
(you don't have to strictly follow this form)

**Describe the bug**

`select NOT(1);` is not working properly. 

**How to reproduce**

mysql> select NOT (1);
ERROR 1105 (HY000): Code: 5, displayText = Unsupported expression: NOT (1), type: UnaryOp { op: Not, expr: Nested(Value(Number("1", false))) }.

**Expected behavior**

clickhouse: 

datafuse :) select NOT (1);

SELECT NOT 1

Query id: f7b4a389-ccad-43dc-83f6-dd3475560074

┌─not(1)─┐
│      0 │
└────────┘

1 rows in set. Elapsed: 0.002 sec.

**Comment by b41sh** [comment]
assign

**Comment by jyizheng** [comment]
@b41sh  Sorry, I didn't realize it has been assigned to you. Thanks for your interest though. I will try to come up with more issues like this.

**Comment by b41sh** [comment]
> @b41sh Sorry, I didn't realize it has been assigned to you. Thanks for your interest though. I will try to come up with more issues like this.

ok, I can do others
