### ISSUE TITLE
[test-infra] Add Contributor License Agreement assistant (CLA assistant)

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#679]
**Summary**

Like:
ClickHouse: https://yandex.ru/legal/cla/?lang=en
TiDB: https://cla-assistant.io/pingcap/tidb?pullRequest=16303
OceanBase: https://github.com/oceanbase/oceanbase/pull/5

**Comment by PsiACE** [comment]
See: https://cla-assistant.io/ or https://github.com/cla-assistant/github-action

**Comment by PsiACE** [comment]
pls assign this to me

**Comment by PsiACE** [comment]
nice, I even want to create a rust version of the bot

**Comment by BohuTANG** [comment]
@PsiACE  
FYI, There is a Rust bot:
https://github.com/rust-lang/triagebot

**Comment by PsiACE** [comment]
I think this issue can be closed
