### ISSUE TITLE
[platform] Multi architecture Docker image support

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/datafuse#683]
**Summary**
Description for this feature.
Currently we only support amd64 architecture fuse-query docker image,  and we should support multiple cpu architecture
https://hub.docker.com/r/datafusedev/fuse-query/tags?page=1&ordering=last_updated

Desired:
https://hub.docker.com/_/rust?tab=tags&page=1&ordering=last_updated

**Comment by sundy-li** [comment]
Now we have `fuse-query` and `fuse-store` and `fuse-benchmark`, the dockerfile should take consider of them in entrypoint.
