### ISSUE TITLE
Can't build datafuse

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/datafuse#688]
Make sure that `git diff` result is empty and you've just pulled fresh master, and run first:
```text
$ make setup
```

**Operating system**

OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

```
OS: Fedora 34 (Workstation Edition) x86_64 
Kernel: 5.12.8-300.fc34.x86_64 
```

**rust version**
```text
$ rustc --version
rustc 1.54.0-nightly (bacf770f2 2021-05-05)
$ cargo --version
cargo 1.53.0-nightly (f3e13226d 2021-04-30)
```

**Datafuse git version**

Just `https://github.com/datafuselabs/datafuse.git, branch = master, rev = 14a78f5b26d040fc4095363229516e62d54ba78e`

**Error Info**

```
Caused by:
  failed to load source for dependency `async-raft`

Caused by:
  Unable to update https://github.com/drmingdrmer/async-raft?rev=cf40344f66fdcb6cde160b3e5671ff87c88f2af8#cf40344f

Caused by:
  object not found - no match for id (cf40344f66fdcb6cde160b3e5671ff87c88f2af8); class=Odb (9); code=NotFound (-3)
```

**Comment by BohuTANG** [comment]
Thanks for the reporting.
Maybe we should fork async-raft to datafuselabs? Cc @drmingdrmer

**Comment by drmingdrmer** [comment]
Yes. I'd transfer ownership to this organization.
