### ISSUE TITLE
[test-infra] Run perf test when comments

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#692]
**Summary**
Performance test is not needed for some PR, such as document or others little changes.
It should be run if we comments under a PR:
`/runperf`

**Comment by BohuTANG** [comment]
![image](https://user-images.githubusercontent.com/172204/120420309-b68aea00-c396-11eb-8c47-17de4768f5e8.png)
Prefered ClickHouse style, but not sure how do it.
https://github.com/ClickHouse/ClickHouse/pull/24734#partial-pull-merging

**Comment by akuzm** [comment]
> ![image](https://user-images.githubusercontent.com/172204/120420309-b68aea00-c396-11eb-8c47-17de4768f5e8.png)
> Prefered ClickHouse style(in fuse-bots), but not sure how do it.
> [ClickHouse/ClickHouse#24734 (comment)](https://github.com/ClickHouse/ClickHouse/pull/24734#partial-pull-merging)

We post these checks through "Statuses" API https://docs.github.com/en/rest/reference/repos#statuses

**Comment by BohuTANG** [comment]
Thanks @akuzm, it will be useful.
By the way, can't find these CI scripts in ClickHouse, is it used internally?

**Comment by akuzm** [comment]
> Thanks @akuzm, it will be useful.
> By the way, can't find these CI scripts in ClickHouse, is it used internally?

Yes, this part is in the internal repo. We use pygithub and its `create_status` method.
