### ISSUE TITLE
`common_exception::ErrorCodes::message()` overrides `display_text` if `cause` is not `None`

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#712]
**Summary**

The problem is once the field `cause` is set, there is no way to display `display_text`, which may provide additional key information about the error genesis.

https://github.com/datafuselabs/datafuse/blob/668ef027b6f4bb713115edc2c7b1db7f30c9184e/common/exception/src/exception.rs#L45-L50

**Proposal**

`ErrorCodes::message()` returns both `cause` and `display_text`.

**Comment by drmingdrmer** [comment]
@zhang2014 any advices? 🤔

**Comment by zhang2014** [comment]
@drmingdrmer maybe we can remove `cause`?

**Comment by drmingdrmer** [comment]
> @drmingdrmer maybe we can remove `cause`?

Aye Captain! 

Done removing `cause` in #719
