### ISSUE TITLE
[tests] Tests support error code match rather than error text.

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#717]
**Summary**
Tests support error code match rather than error text.

```
SELECT x, number FROM system.numbers LIMIT 1; -- { serverError 47 }
```

ClickHouse: https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/00002_system_numbers.sql#L9-L14

**Comment by sundy-li** [comment]
BTW, the testing result is displayed via table, maybe it's good to make it display as normal text.

MySQL/Oceanbase style: https://github.com/oceanbase/oceanbase/blob/master/test/mysql_test/test_suite/join/r/mysql/nested_loop_join_right_null.result

**Comment by BohuTANG** [comment]
ok, make sense
