### ISSUE TITLE
[CI] License Style check

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#724]
**Summary**
1. New contributors always forget to add the license comments in creating new rust file.
2. Vscode and Clion have the feature to auto-import used imports. This will break the file style. 

Better to make a check for this.
```
use common_exception::ErrorCodes;
use common_exception::Result;

// Copyright 2020-2021 The Datafuse Authors.
```

**Comment by BohuTANG** [comment]
This action can do it:
https://github.com/marketplace/actions/license-checker
