### ISSUE TITLE
[style] Rename trait type names from `I$Name` to `$Name`

### ISSUE THREAD

**Issue by TennyZhuang** [datafuselabs/datafuse#727]
**Summary**

E.g: rename `ITable` to `Table`. There is no point to add `I` prefix before a trait.

In rust, A trait type has two usages: 

1. Template argument constrait: like `Where T: Table`, we can know Table is a trait as soon as we see it. 
2. Trait objects: like `Box<dyn Table>`, dyn trait requires exiplit dyn keyword, there is also no confusion at all.

For the reason above, trait named with `I$Name` is meaningless.

**Comment by sundy-li** [comment]
This is from `golang` and `cpp` style, I vote for this change since it's meaningless to keep the prefix `I` for Trait in rust.

 cc @drmingdrmer

**Comment by drmingdrmer** [comment]
For me, the greatest benefit is knowing at first sight what kind of symbol it is.

(Maybe) makes it easier to search for something through plain text, e.g., when you do not know the exact name of it.

(Maybe) the prefix "I" can reduce name conflicts.

Having one more letter does not bother me, although this is not very rust.

Vote for keeping it :DDD

**Comment by dantengsky** [comment]
I prefer not to use the "I" prefix on traits.

**Comment by BohuTANG** [comment]
Thank you very much for this suggestion, from  rustacean view should not have I.
But I prefer to keep I:
For the people who reading the codes and not familiar with rust, at least this is more intuitive.

Vote for keeping I.

**Comment by leiysky** [comment]
I vote for the idiomatic style `Table`. 🚀

**Comment by tisonkun** [comment]
Vote for this change. It is from [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), which is really redundant for modern development environment.

Type is explicit or can be easily identified by "find definition". We have advanced too much from text only ages.

**Comment by BohuTANG** [comment]
Wow, votes status:
rename: 4
keep: 3

But datafuse have some conflicts after rename:
trait IDataSource
struct Datasource

If we rename IDataSource to DataSource, how to deal the struct name?

**Comment by dantengsky** [comment]
Remove `IDataSource`, use `struct DataSource` directly? (replace `Arc<dyn IDatasource>` with `Arc<DataSource>`). 

Till we have multiple impls for an "IDataSource", and at that time we will have different names for impls naturally.

**Comment by drmingdrmer** [comment]
IMHO here the discussion should not be about which style is better, but be about whether it's a good time to apply this change.

Changing it brings in extra refactoring work and name/type conflict.
Leaving as it is makes nothing better or worse.

**Comment by dantengsky** [comment]
If we do wanna follow the naming convention or "[guideline](https://rust-lang.github.io/api-guidelines/naming.html)": 


The sooner the better.


With the supports of IDE, and some namespace tweaking:  8c7888a757643a2df496d83075e2353b3ea0d52a

**Comment by BohuTANG** [comment]
> If we do wanna follow the naming convention or "[guideline](https://rust-lang.github.io/api-guidelines/naming.html)":
> 
> The sooner the better.
> 
> With the supports of IDE (and some manual namespace tweaking), it's no big deal :
> 
> [8c7888a](https://github.com/datafuselabs/datafuse/commit/8c7888a757643a2df496d83075e2353b3ea0d52a)

It's ok to me.
Just do it.

**Comment by dantengsky** [comment]
Roger that

**Comment by TennyZhuang** [comment]
Hi, any update here?

**Comment by BohuTANG** [comment]
I guess @dantengsky PR can be opened again at any time

**Comment by dantengsky** [comment]
@TennyZhuang @BohuTANG  I'd like to re-open the PR (rebased with master branch) later today.

**Comment by BohuTANG** [comment]
Cool, Thanks.
Let's more rustacean!

**Comment by jyizheng** [comment]
Sound great to me to follow the guideline.
