### ISSUE TITLE
How to run tests step by step?

### ISSUE THREAD

**Issue by jovany-wang** [datafuselabs/datafuse#732]
We doesn't clear how to run tests step by step on document. 
For example, Following the 2 commands from document will get an error about unable to connect mysql.
![image](https://user-images.githubusercontent.com/19473861/120825898-6f664a00-c58c-11eb-8ae1-ed6f83f0d198.png)

**Comment by BohuTANG** [comment]
Stateless test required:
$cargo build
$./scripts/deploy/fusequery-standalone.sh
$cd tests
$./fuse-test

We will make the tests documents more clearly, thanks for the report.

**Comment by BohuTANG** [comment]
Maybe we need a script that can be launched the stateless tests with one click locally

**Comment by zhang2014** [comment]
Maybe we should support `make stateless test`? It will automatically run the following commands:
- cargo build
- ./scripts/deploy/fusequery-standalone.sh(with random port)
- cd tests
- ./fuse-test (with random port)

**Comment by BohuTANG** [comment]
make test
it will run unit test and statesess test both
