### ISSUE TITLE
[arrow] Bump modulus to arrow SIMD vectorized implementation 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#735]
**Summary**
After the upstream [Add (simd) modulus op](https://github.com/apache/arrow-rs/pull/317/files), we can change the self define modulus to the SIMD vectorized implementation:
https://github.com/datafuselabs/datafuse/blob/6f7e195f791642a4ed05ce4bf07f011dd91dc6a2/common/datavalues/src/data_array_arithmetic.rs#L66-L71

**Comment by sundy-li** [comment]
cc @taiyang-li
