### ISSUE TITLE
[deps] Move sqlparser-rs to datafuse-extras

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#743]
**Summary**
To fixed the fuzz crashed, it's time to move it to [datafuse-extras](https://github.com/datafuse-extras).

issues:

https://github.com/ballista-compute/sqlparser-rs/issues/314

**Comment by sundy-li** [comment]
Other options [nom](https://github.com/Geal/nom), [pest](https://github.com/pest-parser/pest)?

**Comment by BohuTANG** [comment]
> Other options [nom](https://github.com/Geal/nom), [pest](https://github.com/pest-parser/pest)?

If we have a need to modify but upstream not reponse, usually put it to the extras
