### ISSUE TITLE
[style] Rename trait type names from $Name to I$Name

### ISSUE THREAD

**Issue by TennyZhuang** [datafuselabs/datafuse#744]
**Summary**

Due to the discussion and PR from #740, the result is that I prefix is important for readability .

A codebase should be consistent. it’s important to keep the same style, please rename trait without I to I$Name

such as

* pub trait ResultExt
* pub trait ExprRewriter
* pub trait ExpressionVisitor
* pub trait ToErrorCodes
…

And write some lint rules in CI to disable trait without I prefix in codebase.

**Comment by TennyZhuang** [comment]
We should choose any style as soon as possible. The changes will be larger and larger while the codebase increasing.

**Comment by BohuTANG** [comment]
Hello @TennyZhuang 
Thanks for the suggestion.
To rename is easy for datafuse codebase, we will consider it next week.
Code style is also important!
