### ISSUE TITLE
Return default value when aggregating empty data

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#771]
(you don't have to strictly follow this form)

**Describe the bug**

```
mysql> select sum(number) from numbers(100) where number > 1000;
Query OK, 0 rows affected (0.01 sec)

mysql> select sumIf(number, number > 1000) from numbers(100);
Query OK, 0 rows affected (0.00 sec)

```

Expect to return null, https://www.db-fiddle.com/f/qDnLWye3pM1thKfx4d8Z2M/0

**Comment by zhaox1n** [comment]
it seems partly different behavior between mysql and clickhouse when aggregation function works on empty data, should  only be consistent with mysql?
