### ISSUE TITLE
[Store] Complete ActionHandler test for: create_table(), drop_table() and get_table()

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#775]
**Summary**

There should be a unit test for `ActionHandler::create_db()`:

https://github.com/datafuselabs/datafuse/blob/fbe6bd8d3f761736ca03a1c932753320cd54e1b8/fusestore/store/src/executor/action_handler.rs#L124-L159

A test should start up an `ActionHandler` with a `Dfs` as backend, and assert expected behavior.
Reference:

https://github.com/datafuselabs/datafuse/blob/fbe6bd8d3f761736ca03a1c932753320cd54e1b8/fusestore/store/src/executor/action_handler_test.rs#L24-L52

**Comment by tangwz** [comment]
As a newbie, May I have a try？

**Comment by drmingdrmer** [comment]
> As a newbie, May I have a try？

Of course! Thank you @tangwz !
Is there any one already working on this? @ariesdevil @dantengsky ?
If not I'm gonna assign this issue to tangwz

**Comment by dantengsky** [comment]
@drmingdrmer  nope. 
@tangwz  Thanks!

**Comment by drmingdrmer** [comment]
@ariesdevil already has working on this issue. The issue status should have been updated... Sorry for that @tangwz

**Comment by ariesdevil** [comment]
Closed by https://github.com/datafuselabs/datafuse/pull/1023
