### ISSUE TITLE
Should we rename ErrorCodes to ErrorCode?

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#778]
**Summary**

`ErrorCdoes` is a struct that defines a single error code, not a collection of error codes

https://github.com/datafuselabs/datafuse/blob/fbe6bd8d3f761736ca03a1c932753320cd54e1b8/common/exception/src/exception.rs#L33-L40

**Comment by BohuTANG** [comment]
+1
cc @zhang2014
