### ISSUE TITLE
[observability] http profiling

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#794]
**Summary**

IOx Profiling is very cool, it brings golang pprof to Rust:
https://github.com/influxdata/influxdb_iox/blob/main/docs/profiling.md

**Comment by PsiACE** [comment]
https://github.com/tikv/pprof-rs

**Comment by BohuTANG** [comment]
> https://github.com/tikv/pprof-rs

IOX using it for http profiling, an interesting projection.
