### ISSUE TITLE
[observability] http tracing

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#805]
**Summary**

Add REST API to rpc/http for showing logs from the web side.

Reference:
https://github.com/tokio-rs/tracing/issues/884
https://github.com/tokio-rs/console
https://github.com/tokio-rs/tracing/tree/master/tracing-opentelemetry

**Comment by BohuTANG** [comment]
This task is easy after https://github.com/datafuselabs/datafuse/pull/879, the REST API can read tracing from system.tracing:
`SELECT * FROM system.tracing`

**Comment by jyz0309** [comment]
I think this issue needs more discussion, for example: What is the format of Json? What content should be kept in the `system.tracing` table to be shown in the api.

**Comment by BohuTANG** [comment]
ok, thank you @jyz0309 
The initial design we can make it work and next to choose the pretty format, how about your thoughts?

**Comment by jyz0309** [comment]
I think you are right. Maybe we can just show the logs in the initial design (v0.5). And in the 0.6 version, we can just format it in the Json.

**Comment by jyz0309** [comment]
> ok, thank you @jyz0309
> The initial design we can make it work and next to choose the pretty format, how about your thoughts?

I think you are right. Maybe we can just show the logs in the initial design (v0.5). And in the 0.6 version, we can just format it in the Json.
