### ISSUE TITLE
if for aggregate functions, has performance problems and is very slow 。

### ISSUE THREAD

**Issue by lideen999** [datafuselabs/datafuse#807]
(you don't have to strictly follow this form)

**Describe the situation**
   The new feature, if aggregator, has performance problems and is very slow
 
as see ：
sql = "SELECT sumif(number, number > 100000 ) FROM numbers_mt(100000000) ;"

result：128.89 MB/s.
┌─sumif(number, (number > 100000))─┐
│                 4999994949950000 │
└──────────────────────────────────┘
1 rows in set. Elapsed: 6.213 sec. Processed 100.00 million rows, 800.72 MB (16.10 million rows/s., 128.89 MB/s.) 

@sundy-li

**Comment by sundy-li** [comment]
Yes, it's not auto vectorized

```
fn accumulate(&mut self, columns: &[DataColumnarValue], _input_rows: usize) -> Result<()>   ---> using simd
fn accumulate_scalar(&mut self, values: &[DataValue]) -> Result<()>  ---> not using simd, need future refactor to make it auto vectorized.
```
