### ISSUE TITLE
Database catalog should shared to multiple sessions

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/datafuse#835]
**Summary**
Database catalog should shared to multiple sessions

- [x] MySQL Handler [#704]
- [x] ClickHouse Handler [#931 ]

https://github.com/datafuselabs/datafuse/blob/064820f75faa3e4ba658377ef1910a9f1d2a0d8c/fusequery/query/src/sessions/context.rs#L46-L64

**Comment by sundy-li** [comment]
`DataSource::try_create()` is expensive for each session, maybe better hold a ref to a global instance.

**Comment by BohuTANG** [comment]
> `DataSource::try_create()` is expensive for each session, maybe better hold a ref to a global instance.

Hi @sundy-li , catalog will be designed as an LRU cache, and it only load the meta which we need by the session, I think @dantengsky  is more professional on this, he is designing on it

**Comment by zhang2014** [comment]
> > DataSource::try_create() is expensive for each session, maybe better hold a ref to a global instance.

> Hi @sundy-li , catalog will be designed as an LRU cache, and it only load the meta which we need by the session, I think @dantengsky is more professional on this, he is designing on it

In this task, we will only share Arc<DataSource> to fuse query all sessions. maybe this should not affect the catalog design ?

**Comment by dantengsky** [comment]
> > > DataSource::try_create() is expensive for each session, maybe better hold a ref to a global instance.
> 
> > Hi @sundy-li , catalog will be designed as an LRU cache, and it only load the meta which we need by the session, I think @dantengsky is more professional on this, he is designing on it
> 
> In this task, we will only share Arc<DataSource> to fuse query all sessions. maybe this should not affect the catalog design ?
> 

That's fine, pls go ahead.
