### ISSUE TITLE
[security] Pull Request Security Audit

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#852]
**Summary**

Add Pull Request Security Audit CI, like tokio did:
https://github.com/tokio-rs/tokio/blob/master/.github/workflows/pr-audit.yml

**Comment by BohuTANG** [comment]
arrow-rs deps flatbuffers = "=0.8.4" vulnerability:
```
Title:         `read_scalar` and `read_scalar_at` allow transmuting values without `unsafe` blocks
ID:            RUSTSEC-2020-0009
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0009
Solution:      No safe upgrade is available!

```

**Comment by dantengsky** [comment]
never heard this before, rust's "ecosystem" is amazing!

**Comment by PsiACE** [comment]
also see https://deps.rs/repo/github/datafuselabs/datafuse

Maybe we could also add `[![dependency status](https://deps.rs/repo/github/datafuselabs/datafuse/status.svg)](https://deps.rs/repo/github/datafuselabs/datafuse)` to README file.

**Comment by BohuTANG** [comment]
> also see https://deps.rs/repo/github/datafuselabs/datafuse
> 
> Maybe we could also add `[![dependency status](https://deps.rs/repo/github/datafuselabs/datafuse/status.svg)](https://deps.rs/repo/github/datafuselabs/datafuse)` to README file.

Interesting and useful.

**Comment by BohuTANG** [comment]
It would be better if arrow-rs upstream to fix it:
https://github.com/apache/arrow-rs/issues/476

**Comment by PsiACE** [comment]
Now we can close this issue
