### ISSUE TITLE
[FR] Provide a simple user API for FuseQuery

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/datafuse#869]
**Summary**
Provide a simple user API for FuseQuery(We can ignore permissions)
- Add user (username, password, salt?)
- Drop user (username, password, salt?)
- Update user password(username, password, salt?)
- Get users info

MySQL authentication method: https://dev.mysql.com/doc/internals/en/authentication-method.html

CC: @dantengsky

**Comment by dantengsky** [comment]
sorry bro, just noticed this FR. I will look into it.

**Comment by dantengsky** [comment]
CC: @zhang2014  
I pushed a draft PR #881, please review the API; any suggestions or requirements, please feel free to comment.
