### ISSUE TITLE
[store] MetaNode support `AddTable`

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#872]
**Summary**

- Create a new BTreeMap in `Meta` to store tables.
- Add a new enum item to `ClientRequest` to support `AddTable` request.
- Add API to `MetaNode` to deal with `AddTable` request.

If the table with the same name presents, `MetaNode` should return the present one and apply nothing to raft state machine.

**Comment by drmingdrmer** [comment]
@ariesdevil and this issue needs an update or close it?

**Comment by ariesdevil** [comment]
Closed by https://github.com/datafuselabs/datafuse/pull/1023
