### ISSUE TITLE
`common/runtime/src/runtime_test.rs` should block until all task quits

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#887]
**Summary**

```
#[tokio::test(flavor = "multi_thread", worker_threads = 8)]
async fn test_runtime() -> anyhow::Result<()> {
    use crate::*;

    let runtime = Runtime::with_default_worker_threads()?;
    runtime.spawn(async {
        let rt1 = Runtime::with_default_worker_threads().unwrap();
        rt1.spawn(async {
            let rt2 = Runtime::with_worker_threads(1).unwrap();
            rt2.spawn(async {
                let rt3 = Runtime::with_default_worker_threads().unwrap();
                rt3.spawn(async {});
            });
        });
    });
    Ok(())
}
```

**Comment by BohuTANG** [comment]
> Hello i am a newbie. I am interested in this,But i'm not sure if it can be done.
> I would like to know run `runtime.spawn()` should block until all task quits ?
> thanks.

Not actually.
We talked `block` here is test purpose only.
For `test_runtime` test, it's async and the it returns immediately when running.
Actually, we need a runtime `join` to block until all the async tasks finished.

**Comment by dust1** [comment]
> > Hello i am a newbie. I am interested in this,But i'm not sure if it can be done.
> > I would like to know run `runtime.spawn()` should block until all task quits ?
> > thanks.
> 
> Not actually.
> We talked `block` here is test purpose only.
> For `test_runtime` test, it's async and it returns immediately when test running.
> Actually, we need a `join` to block until all the async tasks finished.

Thanks for the reply.
I think i get it, only need to modify `runtime_test.rs` and block until all the async tasks finished？
If it is like this, Can I try it?
Thanks.
