### ISSUE TITLE
[Store] Provides a generic KV API 

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/datafuse#900]
**Summary**

Store needs to provide a generic KV API, as a primitive service, which clusters management, user management can be built on. 

functionalities:

- get by key (and by keys)
- put 
- list (by prefix)

**Comment by jyizheng** [comment]
I guess "list" means scan or iterator here.

**Comment by dantengsky** [comment]
yeah right, a range iterative

I guess "list" means scan or iterator here.

**Comment by dantengsky** [comment]
Right, just a range iterator
