### ISSUE TITLE
[Config] Load Environment Configuration after load toml config file

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/datafuse#907]
(you don't have to strictly follow this form)

**Summary**

Currently we are adopting arguments and toml files for fuse-query part configuration, however in k8s or container environment, we should prefer to adopt environment variable as the final configuration

configure kubernetes env variable is not working because fuse query only use fuse-query.toml for its configuration

**Expected behavior**
support configuration based on environment variable and toml file

**Additional context**
codes may change
https://github.com/datafuselabs/datafuse/blob/master/fusequery/query/src/bin/fuse-query.rs#L24-L32

promising library
https://github.com/softprops/envy

**Comment by BohuTANG** [comment]
It seems that structopt `from_args` and `from_args_with_toml` can not be used together for a same arg.
So, it would be better only used ENV args mode on k8s, not using toml file.

I don't think https://github.com/softprops/envy for it, it has args mode only.
