### ISSUE TITLE
[functions] Conditional Functions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#918]
**Summary**

If
Controls conditional branching. Unlike most systems, ClickHouse always evaluate both expressions then and else.
Syntax:
```
SELECT if(cond, then, else)
```

Example:

Query:
```
SELECT if(1, 2+2, 2+6);
```
Result:
```
┌─plus(2, 2)─┐
│          4 │
└────────────┘
```

Query:
```
SELECT if(0, 2+2, 2+6);
```

Result:
```
┌─plus(2, 6)─┐
│          8 │
└────────────┘
```

Reference:
https://clickhouse.tech/docs/en/sql-reference/functions/conditional-functions/#if

**Comment by zhyass** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/if.cpp
