### ISSUE TITLE
[security] mask/remove the user and password for config debug

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#935]
**Summary**

```
[2021-06-28T03:13:49Z INFO  fuse_query] Config { log_level: "INFO", log_dir: "./_logs", num_cpus: 16, mysql_handler_host: "127.0.0.1", mysql_handler_port: 3307, mysql_handler_thread_num: 256, clickhouse_handler_host: "127.0.0.1", clickhouse_handler_port: 9000, clickhouse_handler_thread_num: 256, flight_api_address: "127.0.0.1:9090", http_api_address: "127.0.0.1:8080", metric_api_address: "127.0.0.1:7070", store_api_address: "127.0.0.1:9191", store_api_username: "root", store_api_password: "root", config_file: "" }
```

Remove user/password config from debug.

**Comment by wangzhen11aaa** [comment]
assign me. I will try.

**Comment by wangzhen11aaa** [comment]
assign me.

**Comment by wangzhen11aaa** [comment]
My Original idea is that make some string replacement before the log. (Affects the least codes).
But in mac environment,  I run the `make run` command  did not find 
Config { log_level: "INFO", log_dir: "./_logs", num_cpus: 16, mysql_handler_host: "127.0.0.1", mysql_handler_port: 3307, mysql_handler_thread_num: 256, clickhouse_handler_host: "127.0.0.1", clickhouse_handler_port: 9000, clickhouse_handler_thread_num: 256, flight_api_address: "127.0.0.1:9090", http_api_address: "127.0.0.1:8080", metric_api_address: "127.0.0.1:7070", store_api_address: "127.0.0.1:9191", store_api_username: "root", store_api_password: "root", config_file: "" } message in nohup.out or files under the _log directory.
Then I search the key word `store_api_username` in all  files, and got it in the config.rs. and config_test.rs

-------------------
After replacing these root by *** , and run the make test, some sql in fuse-test (python script maybe) can not pass. with the "Unauthorized user *** ".

Now, many mods are unkonwn for me, changing the default constructure for Config is not a good idea for me.

Need a little help. Thanks.

**Comment by BohuTANG** [comment]
Hi @wangzhen11aaa 
 the easy way is to implement a debug trait and ignore/mask the password fields to display.

**Comment by wangzhen11aaa** [comment]
> Hi @wangzhen11aaa
> the easy way is to implement a debug trait and ignore/mask the password fields to display.
That's a good idea, but where can I find the log?
