### ISSUE TITLE
[ci] cargo clippy should failed when have warnings

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#942]
**Summary**

There are many wanings after patch #764 :
https://github.com/datafuselabs/datafuse/runs/2937392884

The ci should failed when clippy has warnings

**Comment by BohuTANG** [comment]
It's better to run `make lint` local before push the patch
FYI @jyizheng

**Comment by jyizheng** [comment]
Sure. Let me fix these warnings.

**Comment by BohuTANG** [comment]
> Sure. Let me fix these warnings.

I am fixing it :dancers:
