### ISSUE TITLE
[store] general-kv: list by prefix

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/datafuse#954]
**Summary**

Retrieve a list of keys(or key-value pairs) from raft state machine.

reference:

https://github.com/datafuselabs/datafuse/blob/d4447709e730025edc3a23d97a30659da49c91a5/fusestore/store/src/meta_service/state_machine.rs#L318-L322

Unit test examples:

https://github.com/datafuselabs/datafuse/blob/d4447709e730025edc3a23d97a30659da49c91a5/fusestore/store/src/meta_service/state_machine_test.rs#L226-L310

https://github.com/datafuselabs/datafuse/blob/d4447709e730025edc3a23d97a30659da49c91a5/fusestore/store/src/executor/action_handler_test.rs#L138-L208

#900

**Comment by dantengsky** [comment]
hi, There is a  `StateMachine::prefix_list_kv` in PR#881, for (user API get_all_users)

https://github.com/dantengsky/fuse-query/blob/c7501a6de140f38e2c18bffe2fcb936d756e6064/fusestore/store/src/meta_service/state_machine.rs#L363-L375

**Comment by drmingdrmer** [comment]
@ariesdevil
It seems you do not need to do this anymore...

@dantengsky 
This is supposed to be a first shot practice for @ariesdevil

By the way, it'd better return key-value pairs for a list request.

https://github.com/dantengsky/fuse-query/blob/c7501a6de140f38e2c18bffe2fcb936d756e6064/fusestore/store/src/meta_service/state_machine.rs#L369-L376

**Comment by dantengsky** [comment]
@drmingdrmer Yeah right, I am fixing that.

**Comment by drmingdrmer** [comment]
@dantengsky shall we close this issue or keep it open?

**Comment by dantengsky** [comment]
yes, let's close it. (by PR #881)
