### ISSUE TITLE
[function] Type Conversion Functions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#967]
**Summary**

```
toInt(8|16|32|64|128|256)
```

* toInt8(expr) — Results in the Int8 data type.
* toInt16(expr) — Results in the Int16 data type.
* toInt32(expr) — Results in the Int32 data type.
* toInt64(expr) — Results in the Int64 data type.
* toInt128(expr) — Results in the Int128 data type.
* toInt256(expr) — Results in the Int256 data type.

Reference:
https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/

**Comment by wangzhen11aaa** [comment]
/assignme 
This time maybe take a longer time.I do not have any idea about this thing in rust.

**Comment by BohuTANG** [comment]
> /assignme
> This easy-task maybe take a longer time.I do not have any idea about this thing in rust.

It's OK, thank you

**Comment by wangzhen11aaa** [comment]
Let's close this issue.
