### ISSUE TITLE
[Store] Change the operation of database, table and data parts from `meta` to `meta_node`

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/datafuse#993]
**Summary**

The current implementation is to use `meta` directly, which needs to be changed to `meta_node` instead.

cc @dantengsky

**Comment by ariesdevil** [comment]
Yup, if all operations are changed, `mem_engine` can be removed.

**Comment by dantengsky** [comment]
:+1:  

> if all operations are changed,
Pls follow your own plan,  change the meta operations step by step is also fine, IMHO.

**Comment by ariesdevil** [comment]
Closed by https://github.com/datafuselabs/datafuse/pull/1023
